# (PART) Preface {-}
# Why Create Another Writing Guide? {-}
Many undergraduate biology courses include lab reports and other types of __scientific writing.__ This genre is not the same as technical writing, which is the style we see in instruction manuals. It is the type of writing that scientists do every day when they write articles for publication, when they apply for grant funding for their research, and even (less formally) when they write up observations in a lab notebook.

Scientific writing starts with a question. It makes one or more claims related to that question, then provides evidence to support the claim(s). The evidence can be a logically reasoned argument, data collected in an experiment, something that someone else published in the past, or some other trustworthy source of information. The ultimate goal is to convince readers that the writer is asking an important (or at least interesting) question, and has found possible answer to the original question. 

This kind of writing is very different from what most students have done in the past. 

It
There are plenty of books available that tell students how to organize and format these 


## What is the STEM Writing Project? {-}
Lorem ipsum. 


## Why An Open Online Book? {-}
Lorem ipsum. 


## How Things Are Arranged {-}
The chapters are arranged into these Sections. If you get lost, the Table of Contents is always on the left side of the screen.  

* __Lorem ipsum.__. A description.


## Giving Credit Where Due {-}
Lorem ipsum. 

Lorem ipsum. 

This project was funded in part by a grant from the National Science Foundation (ID# here.)

