# Preface {-}
## Welcome! {-}

Many undergraduate biology courses require lab reports and other types of __scientific writing.__ This genre is different from the technical writing we see in instruction manuals for cars, computers, or other machines and tools. Scientific writing is what scientists do every day when they create articles for publication, summarize work they have done for their employer, when they apply for grant funding for their research, and even (less formally) when they write up observations in a lab notebook. Scientific writing is very closely connected with other kinds of __scientific communication__ like oral presentations and scientific posters because the thinking and methods we use to share information are very similar.

Formal scientific communication is very different from what most students have done in the past. It is organized in a very specific way and follows particular rules and conventions. In this Guide we will focus on how to build a lab report that models a journal article. We're using this as our model because most parts of a lab report also appear in other kinds of scientific communication. For example, once you learn how to organize the Introduction to a lab report, you pretty much know how to organize the background section of an oral presentation. Making data figures is another example; the same figure formats used in a lab report can be used in a journal article, oral presentation, or poster.


## How This Guide Is Organized {-}

We think that, when you understand the WHY behind scientific writing, and WHERE it sits in relation to other parts of science, it is easier to understand HOW to write effectively. So this Resource Guide puts scientific writing in a larger context. 

__Part 1__ looks at what makes scientific writing distinctive, and how it is organized to meet its goals. We also explain how to __read__ scientific literature, because that is the fastest way to understand the standards and conventions authors follow in a field. 

__Part 2__ explains how hypotheses and experimental design are connected to scientific writing. We tell you how to turn questions about the world around us into testable hypotheses, then design an experiment that provides reliable data to start answering those questions. 

__Part 3__ is a deep dive into scientific articles and lab reports for biology. We show you what goes in each section, point out where our own students struggle with each section, and suggest ways to avoid common pitfalls. Your own instructors will add their observations and suggestions too. 

__Part 4__ shows you how to summarize, analyze, and present the data collected during experiments. We include a basic guide to statistical analysis, with links to more detailed sources of information.

__Part 5__ explains how to use outside sources to support reports, and how to cite sources accurately.

__Part 6__ helps you start expanding your "scientific writer's toolbox." We show you how to build sound arguments, and assess writing, thinking, and logic more critically. 

__Part 7__ has Resources for Instructors. It may not be part of the student version of the Guide.

The __Appendices__ contain practice cases with examples of lab reports written by other students like you. 


## Why Did We Create An Editable Writing Guide? {-}

There are plenty of good books available already that explain how to organize and format scientific writing. This Guide goes beyond the "what is needed" and "how to do X" steps of writing, and explains some of the "why." As teaching faculty in large introductory biology courses we have watched a LOT of students go through the process of learning to communicate like scientists, and seen certain things come up again and again.

One student frustration we hear over and over is "why do we have to do it this way? Why can't I do it the way I learned before in (put any course you like here)?" We've found that, when we explain some of the logic behind elements of scientific writing, then the format and rules make sense and are easier to follow. Every group of students is different though; what our students want or need to know may not be the same for your school. Having this Guide online lets your instructor modify it to fit your program's particular requirements.


Anothere common complaint we hear is that every teacher has different rules and requirements for scientific writing assignments. We've learned that all of this attention to strict rules actually gets in the way of learning to write like a scientist. For instance, some writing guides still insist that all sentences end with two spaces before the next sentence. This rule is left over from the days of manual typewriters. We think it is silly to lower a student's grade for a missing space if typing skills are not what your teacher is trying to develop. In this Guide we try to avoid repeating rules and requirements that are not essential to learning to write well. We also will point out when there may be differences in opinion. For example, the correct format to use when citing sources is a common (and often heated) point of disagreement. In these situations we will provide what we know to be sound advice and our reasons, but you should follow the guidelines your instructor provides if they differ from ours.

Finally, we will suggest free tools and resources that can help you avoid problems altogether. Going back to citing sources, academic literature uses 8000+ different citation formats. Rather than learn the details of whether semi-colons should be italicized after the journal names (but not after book names) for a particular citation format, we suggest using Zotero or some other citation manager to do that for you. 

In the end, we want you as a scientific writer to feel confident that you know WHAT your goals are, WHY those goals are important, and HOW to get there. Who knows? You may find that you have a hidden talent for it, on which you can build a career. Yet even if you never come to enjoy scientific writing, learning to do it well now will pay off regardless of where your professional path takes you.


## Who Are We? {-}
This Guide was created as part of the __STEM Writing Project__ at Wake Forest University. We are STEM teachers and education researchers who want to make scientific writing a bigger part of students' training. Scientific writing assignments are hard to manage in large introductory classes, and hard to evaluate systematically. This Writing Guide is one of many tools we are developing to help STEM teachers solve this challenge.

If you are interested in being a contributor, [contact us about accessing our GitHub projects](https://github.com/adanieljohnson/stemwritingproject).


## Funding and Support {-}
This project was funded in part by National Science Foundation grant #1712423: Improving Scientific Writing In Undergraduate STEM Classrooms - A Training Program for Students and GTAs Aided By Information Extraction Technology.

