# Table of Contents {-}

The links take you to specific Sections and Chapters. If you get lost, the Table of Contents always is on the left side of the screen.  

* [Part 1: How Scientific Literature Works](#goals100)
    + [Goals of Scientific Writing](#goals100)
    + [Reading Scientific Literature](#reading120)
        - Learn what works: reading as a writer
    + [Three ways to read literature](#readstrats125)

* [Part 2: Hypothesis Testing & Experimental Design](#hypothesis200)
    + [What IS a Hypothesis?](#hypothesis200)
    + [Step by Step Guide: Experimental Design](#expdesign210)
    + [The Vocabulary of Experiments - Variables](#variables215)
    + [The Vocabulary of Experiments - Controls, Replicates](#replicates220)

* [Part 3: Pieces of an Article or Report](#articleparts300)
    + [How articles are organized](#articleparts300)
    + [Title and Abstract](#titles320)
    + [Introduction](#introduction340)
    + [Methods](#methods350)
    + [Results](#results360)
    + [Discussion](#discussion380)

* [Part 4: Summarizing, Analyzing, and Displaying Data](#datatypes400)
    + [Types of Data](#datatypes400)
    + [Summarizing Data: Graphs and Charts 1](#chartsone425)
    + [Summarizing Data: Graphs and Charts 2](#chartstwo426)
    + [Summarizing Data: Photos and Illustrations](#photos430)
    + [Summarizing Data: Data Tables](#tables435)
    + [Basic Biostatistics](#biostats450)
    + [Summary Statistics](#sumstats460)
    + [Statistical Comparisons 1](#compstatsone470)
    + [Statistical Comparisons 2](#compstatstwo473)
    + [Statistical Comparisons 3](#compstatsthree475)
    + [Statistical Models](#models480)

* [Part 5: Using Sources](#sources500)
    + [Supporting facts and arguments with sources](#sourcearguments505)
    + [Paraphrasing Sources, Pt. 1](#paraphrasingone506)
    + [Paraphrasing Sources, Pt. 2](#paraphrasingtwo507)
    + [Paraphrasing Sources, Pt. 3](#paraphrasingthree508)
    + [Citation Formats](#citformats510)
    + [Common Mistakes](#citmistakes515)
    + [Managing Sources with Zotero](#zotero520)

* [Part 6: Your Writing Toolbox](#toolbox600)
    + [Writing Strategies](#strategies610)
    + [How to assess scientific writing critically](#toulmin615)
        - Toulmin model of practical argumentation
        - Finding critical thinking and logic flaws
    + [Finding mechanical flaws](#mechanicalflaws620)
    + [Peer Review methods](#peerreview630)
    + [Step-by-Step Guide: Pre-Submission Checklist](#submissioncheck650)

* [Part 7: Resources for Instructors](#teachertools700)
    + [Bins Scoring Method](#binsscore705)
    + [Commenting on Student Work](#commenting710)
    + [Training GTAs](#tatraining720)
    + [Annotated Bibliography](#bibliography750)

* [Appendices: Practice Cases and Example Reports](#appendix800)
    + [Appendix A. Ecology](#appa810)
    + [Appendix B. Physiology](#appb820)
    + [Appendix C. Cell Biology](#appc830)
