# For Instructors {-}

The __SWP Writing Guide__ is more than just a student guidebook. It is a resource for biology instructors who teach scientific writing to undergraduates or supervise teaching assistants who do.  

The Guide focuses on writing a lab report that models a journal article because the same components are used in other forms of scientific communication too. The general format we describe conforms to the Council of Science Editors (8e) standards, with some revisions that make writing easier for students just starting out. However, this Writing Guide is not designed or intended to meet the needs of every possible audience. A single comprehensive Guide that covers the nuances of every possible STEM writing style would be too difficult for students to read and use. Instead we have [released the framework text under terms of a Creative Commons license](http://url) so instructors can edit, extend or modify it to fit their particular needs and requirements. 

Most of the Guide is written assuming that we are talking directly to individual undergraduate students. To make it easier to read online we have tried to limit text pages to <1000-1500 words. Optional or advanced material is marked as such. 

Some pages have an accompanying __Instructors' Supplement__ section or page that can be deleted from the student edition of the Guide with no loss of content. Where appropriate, the Instructors' Supplement will have a __Pedagogical Theory & Evidence__ section outlining the rationale, published evidence, or local data supporting a particular practice. __Instructional Notes__ are practical tips, tricks, and alternative ways to implement the methods or activities. __Localizing Your Guide__ points out items that instructors should check and modify so their distributed document/web pages align with their local goals or requirements. __Watch-Outs__ are particularly difficult or frequent problems that we or others have encountered, and if we know any, strategies for working around them. 


## Our Goals For Instructors {-}

One of our goals in this Guide is to introduce non-specialist STEM writing instructors to evidence-based principles and practices which they might not know about. When we began examining writing through an educational research lens, we soon learned that the Writing Across the Curriculum/Writing in the Disciplines (WAC/WID) community has produced a large body of evidence about effective writing instructional practices over the last 20-25 years. Yet how we teach STEM students to write rarely reflects the important insights gained from that work. Some very common scientific writing instructional practices do not bear up to close scrutiny, and may actually be counter-productive. 

For example, most instructors make a dozen or more specific comments per page on student reports. Many routinely copy-edit individual sentences. When students ignore most of these comments, it is extremely frustrating for their writing teachers (“why don’t they read my comments?!”) Published WAC/WID studies have shown that the average college student learning a new writing style: 

* can only process and internalize 3-5 substantive comments per written page;
* treats all comments as having equal weight; and 
* is very likely to make the simplest corrections first, assuming these changes benefit the final grade as much as more challenging corrections do.

Given this behavior pattern, instructors would help students grow faster if they focused attention on correcting global and structural flaws before tackling smaller errors. So long as larger flaws remain, any formatting that can be corrected by copy-editing is unlikely to improve the overall communicative quality of the work. This is why we now limit the number of arbitrary rules and requirements, and encourage students to focus on the key elements of writing as a means of communication and argumentation first. It also is why we train our GTAs to limit and prioritize comments.

Based on audience responses in professional presentations, we know that some STEM writing instructors disagree with our approach. We stand by it because there is ample external evidence supporting it, and we have evaluated it thoroughly with our own students. That said we know there will always be room to improve. We encourage healthy debate and discussion, and hope others will share their experiences back with us.


