# Instructors' Guide {-}

We developed this Writing Guide over several years, and are releasing it now as part of a larger set of resources for students and teachers working on scientific writing. 

The general format described conforms to the Council of Science Editors (8e) standards. However this Writing Guide is not designed or intended to meet the needs of every possible audience. It simply is not feasible for a single source to be that comprehensive without becoming too difficult for students to read and use. Instead we have [released a framework text under terms of a Creative Commons license](http://url) that instructors can edit, extend or modify to fit their particular needs and requirements. 

This Guide is written assuming that we are talking directly to individual undergraduate students as the main audience. To make it easier to read online we have tried to limit text pages to <1000-1500 words. Optional or advanced material is marked as such.   

Many pages have an accompanying __Instructors' Supplement__ section or page that can be deleted from the student edition of the Guide with no loss of content. As needed, the Supplement has a __Pedagogical Theory & Evidence__ section outlining the rationale, published evidence, or local data supporting a particular practice. The __Instructional Notes__ are practical tips, tricks, and alternative ways to implement the methods or activities. __Localizing Your Guide__ points out items that instructors should modify so their distributed document/web pages align with local goals or requirements. __Watch-Outs__ are particularly difficult or frequent problems that we or others have encountered, and if we know any, strategies for working around them. 

Anyone interested in writing new material and expanding the master version of this Guide should contact Dr. Dan Johnson about author-level access to the main GitHub repository. 


## Central Philosophy {-}

When we starting looking at lab reports as an educational research subject, we found that some very common scientific writing instructional practices do not bear up to close scrutiny. For example, most scientific writing instructors make dozens of specific comments and frequently copy-edit individual sentences of student reports. Yet a large body of published evidence has shown that this is counter-productive, because an average student: 

* can only process and internalize 3-5 substantive comments per written page;
* treats all comments as having equal weight; and 
* tends to make the simplest corrections first, assuming these changes benefit the final grade as much as more challenging corrections do.

It is more important for students to correct global and structural flaws first. So long as these larger flaws remain, any formatting that can be corrected by copy-editing is unlikely to improve communicative quality of the work. In response we now limite the number of arbitrary rules and requirements and encourage students to focus on the key elements of writing as a means of communication and argumentation first. 

Given the range of responses we have gotten at professional presentations, we know that not all writing instructors agree with our approach. We stand by it because there is ample external evidence supporting it, and we have vetted it thoroughly with our own students. That said we know it can always be better.   We encourage healthy debate and discussion, and hope others will share their experiences back with us.


## Student Pages
* Write sections as if talking directly to one student
* Limit page blocks to 1000 words if possible, MAX of 1500 words
* Tag sections as EXTRA or OPTIONAL or ADVANCED

## Instructors' Supplement 
Section or page with:
* Pedagogical Theory & Evidence
* Instructional Notes
* Localizing Your Guide
* Watch-Outs

# Instructors' Guide {-}

The SWP Writing Guide is for biology instructors who teach scientific writing to undergraduates or supervise teaching assistants who do. The Guide focuses on how to write a lab report that models a journal article because the same components are used in other forms of scientific communication too. Format and style recommendations generally follow the Council of Science Editors (8e) standards, with some revisions that make writing easier for students just starting out. We have intentionally avoided overly specific requirements for reasons explained shortly. 

This Guide is not designed to meet the needs of every possible audience. No one source can be that comprehensive and still be accessible to an undergraduate audience. Instead we crafted a general framework that instructors can download under the terms of a Creative Commons license, then edit to fit their local needs and requirements. 


## What Do We Mean By Scientific Writing {-}

__Scientific writing__ is not the same as technical writing like we would see in instruction manuals for instruments. It is the type of writing that scientists do nearly every day. The goal of scientific writing is to make an argument which convinces readers that the writer is asking an important (or at least interesting) question, and has some interesting insights related to that question.

This genre of writing follows organizational rules and conventions that tell writers what is expected of them, and lets readers find information they need more efficiently. Usually the writer starts by introducing their question and providing some context for thinking about the question. Next the writer outlines the methods and materials they used to probe their question and reports their results in a standard format. In the next part, the writer makes one or more claims related to that question, then used their own findings and other published evidence to support the claim(s). 



## What Assumptions Did We Make in This Guide?  {-}

We want new scientific writers to feel confident that they know WHAT the goals are, HOW to get there, and WHY those goals are important. We hear over and over from our students, "why can't I do it the way I learned before in 'X'?" We found that when we explain the logic behind certain key elements, the format makes more sense and becomes easier for students to master. It is easy to go overboard though. We recommend adjusting the "why" elements of this Guide based on the commonly repeated questions of your local students. 


Overly strict rules get in the way of learning to write like a scientist. We try to avoid requirements that are not essential to learning to write well. 



## Heresies {-}
When we first took a research-centered approach to lab report collection and assessment, one of our earliest discoveries was that some traditional writing conventions simply did not bear up to close scrutiny. 

We have aimed to reduce the number of arbitrary rules and requirements so that students can focus first on the key elements of writing as a means of communication and argumentation. 

Not all writing instructors will agree with our approach. We invite healthy debate and discussion, and anyone who wants to change the text for their students is welcome to do so by forking it on GitHub.

Global and structural flaws are more important for students to correct. Copy-editing and format are not important for novice writers to focus on. 

