# What is Scientific Writing For?

The rest of this Guide details how to organize and create a lab report or other form of scientific communication. Before we dive in though, let's look at the bigger picture, and talk about the __assumptions__ of scientific writing and the __fundamental goals__ that the writer hopes to accomplish.

Scientific writing starts with the assumption that its readers also are scientists (which includes scientists in training like you.) That means authors will assume their readers have certain background knowledge. If the readers do not have that, the author assumes the readers will look for that background on their own. 

Reading is the step to mastering scientific writing.


Details differ, but  The author starts with a question. It can be their own question

The writer makes one or more claims related to that question, then provides evidence to support the claim(s). The evidence can be a logically reasoned argument, data collected in an experiment, something that someone else published in the past, or some other trustworthy source of information. The ultimate goal is to convince readers that the writer is asking an important (or at least interesting) question, and has found possible answer to the original question. 

This kind of writing is very different from what most students have done in the past. 

It
There are plenty of books available that tell students how to organize and format these 

# Who, Why, How {-}
## What is the STEM Writing Project? {-}
Lorem ipsum. 


## Why An Open Online Book? {-}
Lorem ipsum. 


## How Things Are Arranged {-}
The chapters are arranged into these Sections. If you get lost, the Table of Contents is always on the left side of the screen.  

* __Lorem ipsum.__. A description.


#Acknowledgments {-}
## Giving Credit Where Due {-}
Lorem ipsum. 

Lorem ipsum. 

## Funding and Support {-}
This project was funded in part by a grant from the National Science Foundation (ID# here.)

