# Reading As a Writer

__Reading__ scientific writing is the key to __writing__ well.

As we said earlier, most scientific writers assume their readers know the vocabulary and accepted styles and formats for sharing information in their field. The best way to learn the conventions and assumptions of any field is to read published work from that field. Instead of just looking at the scientific arguments or conclusions though, also pay attention to how the author has organized and presented the information. 


## Can We Trust the Authors?
Scientists are skeptics who rarely accept something without evidence. One of the first questions you should ask as a skeptic-in-training is, "how do I know the author is trustworthy? Are they following accepted conventions of the field? How do I know they are not misleading me?" This is why we put so much emphasis on using peer-reviewed sources. "Peer review" means that the article you are reading was sent to two or more members of the scientific community who work in that particular field. They have read it, and told the author where to make corrections so the article meets the standards and expectations of their field. The editor of the journal may have given the author recommendations too. 

When the editor approves an article for publication, they are saying "other scientists in this field read this article and they agree with me that it meets our expectations and assumptions, and has something worthwhile to say." That does not mean what the article says is always 100% correct. Mistakes do slip past the reviewers and editors, which is why you should always look at more than one article. 






