# Practicing Strategic Reading
This is a generic exercise that you can use to practice strategic reading. The basic steps are the same for many different reading goals. Your instructor may do this as a class exercise, but you can practice anytime on your own.

Once you have the articles, the exercise should take less than 1 hour. It is short intentionally, so you are less likely to get bogged down or frustrated.

1. PICK ONE READING GOAL that you want to practice. Start with one in the "new to the field" list. Focus on one reading area at a time. It does not help you to try and do it all at once.
2. FIND FIVE PRIMARY ARTICLES that you will use to practice strategic reading. The first time your instructor may give you 5 articles and a specific goal to practice. 
    + If you must find your own articles, locate 1 article related to your goal. Then look at the in-text citations in the relevant section(s) for your goal. Get copies of 4 more cited articles that seem to be related. 
    + Do not worry about whether you have chosen good articles or not; judging their value is part of the exercise. Learning to find primary sources is an important skill on its own that we do not have time to teach you. 
    + To learn more about searching for literature, schedule a meeting with the local Science Reference Librarian.
3. SKIM EACH OF THE FIVE ARTICLES you have chosen. Spend no more than 25 minutes on the 5 articles (5 minutes per article.) Identify and write down 3 pieces of concrete or specific information in EACH article that helps you meet the original stated goal. 
    + For now ignore interesting information that is not relevant to your main goal. 
    + If one of the articles you chose does NOT provide useful information related to your reading goal, rank it "less relevant," and move on to the next article.
4. PICK THE THREE MOST RELEVANT OR INFORMATIVE ARTICLES relative to your original reading goal. Spend no more than 5 minutes on this step.
5. SUMMARIZE WHAT YOU LEARNED from the 3 most relevant or informative articles relative to your original reading goal. Spend no more than 20 minutes on this step. Summarize what you learned from these 3 articles.
    + Do not just list the facts separately. Try to connect the information in the 3 articles together in one coherent argument or story.
6. REVIEW WHAT YOU JUST DID. Where did you struggle or get bogged down? What took longer than it should have? If you had to do this same thing again, what would you change and why? Write down what you noticed so you can review it quickly the next time you have to read primary literature.



TEACHING STUDENTS TO READ LITERATURE MORE DEEPLY

There are many strategies for reading and discussing primary literature. We use the 3-2-1 technique to help students learn how to extract the main content ideas, and prepare to discuss readings. It is adapted from the Purposeful Reading Assignment [Roberts: 2008; Novak: 2011].

The main benefit of this method is that TAs can use the question responses to probe the students' knowledge in follow-up discussion. Students quickly realize that they should work on these questions in advance if they do not want to appear unprepared. Another benefit is that it provides a way to get quiet students involved without calling on them directly. 

It is described here and in the Biology Core Resource Guide as a method for primary literature reading assignments, but with adjustments it can be applied to almost any pre-class reading or activity. The steps:
1.	First, a student reads the assigned article. 
2.	Each student chooses and describes the THREE most important aspects of the article. They can be key findings, conclusions, concepts, or issues raised. The student writes a short 1-2 sentence justification for why each item they chose is one of the 3 most important aspects of the reading.
3.	Each student identifies TWO aspects of the reading they do not understand. They probably will identify more than two confusing elements. They should put them in priority order, and decide which two are the most important, then write a brief explanation of how/why these confusing aspects interfered with their general understanding of the reading. 
4.	Each student poses ONE follow-up question to the text’s author. The answer to this question should go beyond the reading content and should not reflect the 2 areas of confusion above. 
5.	All students bring their 3 key points, 2 points of confusion, and 1 follow-up question with them to class on the day the article is discussed, and use them as reference material.

Different readers are going to choose different key points. Asking for a group to share theirs with each other brings more of the key points to the surface without putting any one person in the position of having to identify them all. Also, students see how others are thinking about the same information in different ways.

Asking for students' two confusing points can uncover points the entire group misunderstands or is struggling with. Also, we rarely understand fully a reading assignment that is outside our comfort zone. Reflecting explicitly on what we do not know and how it affects our understanding makes confusion an acceptable part of learning, not something we must hide. 

The final follow-up question surfaces a group’s thoughts about implications or applications of the reading assignment, and is a good indicator of the depth to which students understood the author’s message. 
