# (PART) How Scientific Literature Works {-}
# What Do We Mean By Scientific Writing? {-}

__Scientific writing__ is not the same as technical writing. Technical writing is the type we would see in instruction manuals for scientific instruments or the owner's manual for a car. Scientific writing is the kind that scientists use nearly every day. Their goal is to make an argument which convinces readers that the writer is asking an important (or at least interesting) question, and has some interesting insights related to that question.

Organizational rules and conventions of this genre tell authors what they are expected to do or give to readers, and lets readers find information they need more efficiently. Usually the writer starts by introducing their question and providing some context for thinking about the question. Next the writer outlines the methods and materials they used to probe their question and reports their results in a standard format. In the next part, the writer makes one or more claims related to that question, then used their own findings and other published evidence to support the claim(s). 

The rest of this Guide explains how to organize and create a lab report or other form of scientific communication. This kind of writing probably is very different from what you have done in the past, so before we dive in, let's step back and talk about the bigger picture. What __goals__ does a scientific writer hope to accomplish (and how will they get there), and what __assumptions__ do they make about their audience?


## Scientific Writing Has Specific Goals {-}

The goal of scientific writing is to make an argument which convinces readers that the writer is asking an important (or at least interesting) question, and has found a possible answer to the original question.

Usually the writer starts by introducing their question. It can be their own question, a problem that many scientists working in the field know about, or an observation that cannot be explained by the current understanding within the field. The writer provides some context for thinking about the question, usually by describing (and citing) what others have seen and said. 

Next, if the writer has conducted any new research studies, they will outline what methods and materials they used, providing enough detail for readers to judge whether or not their results can be considered reliable, and report what they observed. Writing that includes new studies is what we call __primary literature__. Writing that summarizes what others have written or done without doing new studies is what we call __secondary literature__, or __review literature__. 

Next the writer makes one or more claims related to that question, then provides evidence to support the claim(s). The evidence can be data collected from a series of experiments, a logically reasoned argument, something that someone else published in the past, or some other trustworthy source of information. This step is when the writer actually tries to show they have found a possible answer to the original question. It also is when a good writer will outline the potential limitations of their own argument, and lay out new questions to think about.

Some review literature is meant to summarize a large amount of data, rather than make claims in support of a particular field or point of view. An example of this is the 5th Assessment Report (AR5) from the Intergovernmental Panel on Climate Change (http://www.ipcc.ch/report/ar5/.) AR5 is the definitive source of data on global climate change up to 2013. AR5 was written by IPCC, but it brings together data from primary literature published by other scientists too. 


## Scientific Writing Makes Assumptions About the Audience {-}

The first assumption is that its readers are scientists working in the same or a closely related field. Each field has its own vocabulary, accepted styles and formats for sharing information. Authors assume their readers know the conventions of their field, including how and where important information is located in written work. Authors also assume their readers know certain general background concepts in their field. If the readers do not, they assume their readers will look for that background on their own. 

This is why so many students struggle at first reading scientific articles: they don't yet know this assumed knowledge. You are not alone; even long-time scientists can find it hard to switch to a new field. The easiest way to learn the conventions and assumptions of any field is to dive in and try to read published work from that field. Instead of looking at what the scientific arguments or conclusions are though, look at how it is __structured__. 

* How is information organized and presented? 
* What is assumed prior knowledge? 
* Look at multiple articles from the field: what vocabulary terms come up repeatedly? 

Answering these questions for just a few articles in a field can uncover many of the assumptions that authors in that field make.


## Scientific Writing Relies On a Specialized Vocabulary {-}

Some words and phrases are unique to STEM, or used very rarely outside of STEM contexts. For example, it would be very unusual to hear someone use the phrase "positive control" in daily conversation, but in scientific writing (especially in biology), this phrase has a very specific meaning. 

Other terms have a different meaning in general use vs. a STEM context. For instance we use the word "theory" in general conversation to describe a rough idea or educated guess for how something works. In STEM fields, theories are rigorously and repeatedly tested principles that describes how the world around us operates. In STEM, theories are just below laws (like the law of gravity) in terms of certainty. 

Another example is the word "significant." In general conversation this means something seems important enough to notice. For scientists, it means the differences between two or more groups has been evaluated using statistical tests, and the test indicates that the two groups are probably not different just due to random chance. The word "significant" is so loaded with hidden meaning that many scientists never use it EXCEPT when describing the results of statistical tests. 


## What is NOT Scientific Literature? 

Popular literature refers to any literature that is not peer-reviewed or fact-checked for accuracy. The accuracy and quality of popular literature varies along a continuum. At one end are magazines like Time, Newsweek, and The Economist, and newspapers like the Wall Street Journal. They are well known for having high standards and checking their facts before publication. Often they are as rigorously reviewed as scientific literature. At the other extreme are National Enquirer, TMZ, and other print and web sources that check facts rarely if at all. Somewhere in between these extremes are crowd-sourced resources like Wikipedia that have varying degrees of oversight and accuracy-checking. 

None of these are accepted as part of the scientific literature. You should not use popular sources or web sites as sources for information or as citations in scientific communication. 

Most web sites are not considered scientific literature because they are not peer reviewed. The exceptions to this are curated web databases like Genbank (where data scientists regularly check data for accuracy) and official pages of scholarly projects and federal government agencies. 


## Where to Learn More 

[Is It Primary Literature?](https://www.youtube.com/watch?v=3o35J2QihJY)

