# Practicing Scientific Literature Reading

## Exercise 1: Speed Summary

This is a generic exercise that you can use to practice strategic reading. Your instructor may do this as a class exercise, but you can practice anytime on your own. The basic steps are the same for many different reading goals. 

Once you have the articles, the exercise should take less than 1 hour. It is short intentionally, so you are less likely to get bogged down or frustrated.

1. PICK ONE READING GOAL [\(listed here\)](http://url) that you want to practice. Start with one in the "new to the field" list. Focus on one reading area at a time. It does not help to do them all at once.
2. FIND FIVE PRIMARY ARTICLES that you will use to practice strategic reading. The first time your instructor may give you 5 articles and a specific goal to practice. 
    + If you must find your own articles, locate 1 article related to your goal. Then look for in-text citations in the section(s) that are relevant to your goal. Get copies of 4 more cited articles that seem to be related. 
    + Do not worry about whether you have chosen good articles or not; judging their value is part of the exercise. 
    + Learning to find primary sources is an important skill on its own. If you have trouble searching for literature, schedule a meeting with your local Science Reference Librarian.
3. SKIM EACH OF THE FIVE ARTICLES you have chosen. Spend no more than 5 minutes per article (25 minutes total.) Find and write down 3 pieces of concrete or specific information in EACH article that helps you meet the original stated goal. 
    + For now ignore interesting information that is not relevant to your main goal. 
    + If one of the articles you chose does NOT provide useful information related to your reading goal, rank it "less relevant," and move on to the next article.
4. PICK THE THREE MOST RELEVANT OR INFORMATIVE ARTICLES relative to your original reading goal. Spend no more than 5 minutes on this step.
5. SUMMARIZE WHAT YOU LEARNED from the 3 most relevant or informative articles relative to your original reading goal. Spend no more than 20 minutes on this step.
    + Do not just list facts. Connect the information in the 3 articles in a coherent argument or story.
6. REVIEW WHAT YOU JUST DID. Where did you struggle or get bogged down? What took longer than it should have? If you had to do this same thing again, what would you change and why? Write down what you noticed so you can review it quickly the next time you have to read primary literature.


## Exercise 2: 3-2-1 Technique

This technique is adapted from the Purposeful Reading Assignment [Roberts: 2008; Novak: 2011]. We use it regularly as a pre-class assignment to help students extract the main content ideas and prepare to discuss readings. We like it because instructors can use the question responses to guide the follow-up discussion, and call on students without them feeling unprepared. 

The description assumes you are reading primary literature. With a little adjustment it can be used for almost any pre-class reading or activity. 

The steps:

1. Read the questions below FIRST, then read the assigned article with those questions in mind. 
2. Choose and describe the THREE most important aspects of the article. They can be key findings, conclusions, concepts, or issues raised. Write a short 1-2 sentence justification for why each item you chose is one of the 3 most important aspects of the reading.
3. Identify TWO aspects of the reading you do not understand. You may identify more than two confusing elements. If so, put them in priority order, and decide which two are the most important. Write a 1-2 sentence explanation of what you do understand vs. what is confusing. 
4. Pose ONE follow-up question to the text’s author. The answer to this question should not be in the reading and should not be the same as the 2 areas of confusion above. The goal is to think beyond the reading content.
5. If you are discussing the article in class, bring your 3 key points, 2 points of confusion, and 1 follow-up question with you to class on the day the article is discussed, and use them as reference material.

Different readers are going to choose different key points. By discussing them as a class, you will get to see what others thought were important, without anyone having to find everything. The two confusing points may be standing in the way of your own understanding, but very likely several other people are struggling with the same points. Also, we rarely understand fully an article that is outside our comfort zone. Reflecting explicitly on what we do not know and how it affects our understanding makes confusion an acceptable part of learning, not something we must hide. 

The final follow-up question helps you start to think about implications or applications of the reading assignment, and is a good indicator of the depth to which you understand the author’s message.


## Exercise 3: Science Writing Heuristic

The __science writing heuristic__ (SWH) is adapted from a method published by Keys and Hand [Keys, 1999]. This method takes more time but helps you extract much more information. 

It is a set of 5-6 general questions that you can use to break down and interpret almost any article. 

* What did the authors know before starting?
* What did they do?
* Why did they do it?
* What did they observe?
* What do they think it means?
* What was good about the article? What could have been improved?

Each question has specific sub-questions. A common mistake many students make is to answer every general and specific question even if it is not appropriate for the article. Not every specific question will be appropriate for every article. If one of the specific questions does not apply, move on. Focus on being able to answer the general questions fully. 

1. What is already known? What is not known?

Experiments are based on assumptions and prior knowledge or observations that point towards a testable hypothesis. Some information may be common knowledge. Other concepts may be known only to specialists in the field. Look for answers to these questions in the Introduction. Some background may be in the Discussion section too. 

* At the time the article was written, what was already known about the particular organism, test subject, or model system being studied? 
* What questions come to your mind when you think about the model system that the authors used?

__Tip:__ At first you may have to look up background information that is common knowledge among specialists in the field. The more you read about a topic, the less you will have to stop and look up. 

2.  Why did the individuals who conducted the study choose their particular question? 

Authors may list several questions that have not been answered, but choose one to study. 

* What questions did the author(s) point out?  Which question(s) did they decide to try and answer with this study?  Why?
* What specific model system are they using to seek answers or test hypotheses? Why that model and not another?
* What general hypothesis did they test, and how? Why did they choose that hypothesis? 

3.  What did the individuals who conducted the investigation do? 

Look for answers to these questions in the Methods section. Some additional information may be included near the end of the Introduction.

* What was their testable hypothesis? What were the predictions made based on that hypothesis?
* What experimental methods were used? Are there other methods that might have given better information, or more accurate results?
* What were the independent and dependent variables? 
* What were the controls? Were these controls sufficient to cover all possibilities?
* Given on the methods used, what were all of the possible outcomes (not just the ones that were actually observed)? 

4.  What were the main results? 

Look for answers to these questions in the Results section. You also will need to read and interpret the tables and figures. Look at the statistical analyses to gauge the reliability of their results.

* What general trends did the authors see? 
* Did they see any data points that differed in any major way from the general trends? 
* How big of an effect did they see? Were those effects significant?
* Can we trust the reported data?

5.  What do the results mean? Why are the results important? 

Look at the Discussion to answer these questions.

* What are the authors claiming? Are their claims sound, reasonable, and supported by evidence? 
* Is the authors’ evidence for their claim(s) strong or weak? Are there other ways to interpret their observations? 
* Is there any other reasonable explanation for the observed outcome besides what the author claims? If so, why do the authors think their explanation is the correct one rather than one of the alternatives? 
* What is still unclear or uncertain?
* What experiment or other evidence would provide evidence that this author’s claims and conclusions probably are not true?
* Does evidence from outside sources support the author’s claims and conclusions? If yes, in what way? If not, is there an explanation for the contradiction, or is there some future experiment that could be done to determine which claims are correct? 
* What new information has been learned as a result of conducting this experiment or set of experiments?
* What is the most logical next step? What new questions or experiments does this work suggest?

6.  What was good? What could be improved?

Reading papers also helps you understand the mechanics of writing. These questions can help you see how authors’ decisions impact clarity, and thus a paper’s effectiveness overall.

* What parts of the paper were particularly good? What could have been made better, and how?
* How did the authors summarize numerical data so it is easier for another reader to understand? 
* How were the results analyzed? What statistical analyses were used?
* If graphs were included, were they clearly labeled? Easy to read? Easy to understand? Explained in the legend or text?
* If tables were included, were they clear, easy to read and understand, and properly explained?
* What about the writing style made the paper easier or harder to read and understand? 


## Where to Learn More 

Two short videos explaining how to read articles out of order (Abstract then Discussion, etc.)

* [Quick Scanning Articles](https://www.youtube.com/watch?v=3q9xTQIr4FM)
* [Finding Key Points and Taking Notes on Articles](https://www.youtube.com/watch?v=t2K6mJkSWoA)

Keys, CW, Hand, B, Prain, V, Collins, S. 1999. Using the Science Writing Heuristic as a tool for learning from laboratory investigations in secondary science. _Journal Of Research In Science Teaching._ 36(10): 1065-1089. 

Novak GM. 2011. Just-in-time teaching. _New Directions for Teaching and Learning_. 2011(108): 63–73.

Roberts JC, Roberts KS. 2008. Deep reading, cost/benefit, and the construction of meaning: Enhancing reading comprehension and deep learning in sociology courses. _Teaching Sociology_ 36(2):125-4.

