# How to Construct a Good Argument

Something we talk about a lot in scientific writing are arguments. In this instance, an argument is not a verbal fight, but a statement or claim backed by logical reasoning and evidence. In 1958, the British philosopher and educator Stephen Toulmin published "The Uses of Argument," a book in which he laid out a practical framework for deconstructing and analyzing arguments. We also can use his method to __construct__ better scientific arguments.

Toulmin broke down arguments into six interrelated components. To make it simpler, we will combine some and give them more familiar names. 

Every arguments has a central __claim or conclusion__. Usually the claim will be obvious, but sometimes it will be implied or inferred.

The claim or conclusion will be based on __evidence__. Evidence consists of one or more __observed facts__. The facts may be direct observations made by the writer, or they can be prior observations made by someone else. Using both kinds of facts makes for a stronger argument. 

__Reasoning__ is how the observed evidence leads logically to the claim or conclusion. (FYI, Toulmin used the names warrant and backing, not reasoning.)

Sometimes evidence can be interpreted more than one way. A __rebuttal__ is evidence or reasoning that weakens the connection between the observations and the claim/conclusion. 

From these four components we can create four simple but powerful questions to checking the strength any argument we make when writing.

1. Is the claim clear, and based on evidence?
2. Is the evidence clear and relevant? 
3. Is the reasoning leading from evidence to claim sound? Is there another possible explanation?
4. Can the claim be rebutted? Is there conflicting evidence?

We can add one additional question to make this set even more powerful: 

5. What do we NOT know that would clarify our thinking?


## Putting This Framework to Work
Let's use the simplified Toulmin model to assess some (slightly silly) arguments. Suppose you are hiking in the woods with three friends. 

Your first friend says, 
    "I bet there are bears here." 

They just made a claim, but they provided no evidence or reasoning to support it. On its own this is a pretty weak argument. 

If your first friend says, 
    “There’s a bear!” 

They have made a clear claim, and they are implying that they have direct evidence, but you do not know what kind of evidence or how they decided it indicates a bear.

If they say,
    “I see a bear!” 

Now you have a claim and know what kind of evidence they are using, but you still do not know anything about their reasoning. Does your friend actually know what a bear looks like, or how big it is? They might be looking at a raccoon or groundhog. 

Your second hiking partner then says, 
    “There’s a big pile of poop and tracks like a bear makes, so there’s probably a bear around here!” 

There is clear claim, evidence, and reasoning now, but we are not out of the woods yet. Do you trust your second friend to know what a bear's tracks look like?

Now suppose your second friend had said, 
    “There’s a big pile of poop and huge tracks, so there’s probably a sasquatch!” 

They are making a claim that goes against what we have observed in the past. That requires a lot more compelling evidence, and some way to block the rebuttal. Their reasoning is flawed too, because they did not rule out other possible sources (like a bear). 

Your third hiking companion says,
    “There’s a big pile of poop and tracks that look like the picture of bear tracks in the field guide; no other species lives here, and the warden said black bears have been spotted recently. So it’s probably a black bear!” 

Now we have a very robust argument. There is a clear claim based on multiple pieces of evidence, clear reasoning, and information that addresses a possible rebuttal. (Of course, all three of you are now dead because you spent 10 minutes building a robust argument rather than running away from the bear!)


## How To Use This In Your Writing
If you want to improve the quality of your scientific writing, pay close attention to the details of your arguments. Remember, the goal of scientific writing is to make a strong argument in support of a claim using multiple pieces of evidence and sound reasoning. 
