# Supporting Your Arguments With Sources 

## How Things Are Arranged
This is how the Sections and Chapters are arranged. If you get lost, the Table of Contents is always on the left side of the screen.  


# Thinking About Citations and Sources

## Something Is Not True JUST Because It is Published
Being published in one article does not automatically make a statement universally true. The more important a question or broad general statement is, the more evidence is needed to support it.

This is why it is so hard to answer the question, "how many sources does my lab report need?" It depends on the story you are trying to tell, and the argument you are trying to make. Some arguments need more support than others. 

The best way to learn how to judge how many sources you need is to read published literature and look specifically at how citations are used. Foundational statements that are central to the whole story usually have multiple independent supporting sources (no referencing multiple articles by the same author or lab!). Observations by one particular lab or an unusual experimental method might have one citation. 

## How Strong is the Evidence?
Some professional societies and government agencies like the National Cancer Institute publish summary statements that are meant to guide public or health policy. These statements are based on literature in the field, but the authors do more than just list the sources of their information. They include a "Level of Evidence" rating that is determined by an expert panel of reviewers. Say the NCI published a statement saying "walking every day reduces your risk of dying due to four specific cancers [2,3,18; LoE= solid]." This is the highest Level of Evidence that NCI uses. It means the statement is based on data obtained from several well-designed and well-conducted randomized clinical trials within the general population, and the studies report evidence about both benefits and harms. Studies with other levels of supporting research will get a different rating, like "good," "fair," "weak," or even "inadequate." Other agencies and societies will have their  As a writer-in-training you will not need to rate the level or quality of the evidence you cite. However, it IS important to understand that, just because something is published, it does not make it universally true. The more important the question (does walking reduce cancer risk?) the more data we need to make a broad general statement. 

s, however, not always practical to conduct such trials to address every question within the field of screening and prevention. Thus, the PDQ Editorial Board does consider “fair” evidence in estimating the benefits and harms of an intervention in the general population. When the evidence for the benefits and/or harms of an intervention is “inadequate,” the Board states this finding.

Levels of Evidence

Some of the reference citations in this summary are accompanied by a level-of-evidence designation. These designations are intended to help readers assess the strength of the evidence supporting the use of specific interventions or approaches. The PDQ Screening and Prevention Editorial Board uses a formal evidence ranking system in developing its level-of-evidence designations.