# Step by Step Guide to Experimental Design {#expdesign210}

A report describing the results of an experiment is the final step in a chain of events that starts with asking questions. Good scientific writing also depends on good experimental design. The best scientific writing cannot hide poor experimental design and analysis.

When you are first starting out, it helps to follow a systematic, step-by-step approach to designing experiments. The terminology and each of the steps is explored in detail elsewhere in this Guide. 

If you are thinking, "this seems like a lot of extra work," keep in mind that these steps ALSO describe how you develop the content of a good lab report. Working through these steps systematically helps you learn how the pieces fit together in the final written product. Soon you will find yourself jumping back and forth between steps, and considering more than one step at a time. After a while the process will become more or less automatic, and you likely will develop your own workflow.


## Step 1: Collect background information and observations. {-}

Ask yourself:

* What background information is vital to my study? 
* What do I need to know before I can proceed with asking my question? 
* What have other scientists learned that is relevant to answering my question?
* What background will my readers need to know to understand my question, and how I designed my study? 

Some of this information will be included in the first part of your Introduction section.


## Step 2. Decide what specific biological question you want to try to answer. {-}

Do not try to organize it formally yet, just ask yourself what you want to know. Once you have a rough question, rephrase your question in the form of __biological null and alternate hypotheses__. [Hypotheses are explained further here](#hypothesis200). 

The biological hypothesis refers to your expectation of what will happen in the physical world due to a biological process or mechanism. It is a generalized statement explaining how a biological mechanism of interest causes an independent variable to affect a dependent variable.

Usually the alternate half of the biological hypothesis statement will be near the end of the Introduction section of a report or article.


## Step 3. Decide which variables are relevant to the question you are asking. {-}

[Variables are explained further here](#variables215).

What are the __independent variables__? These are the things that you can vary experimentally, or can be used to divide experimental observations or subjects of the study into control and test groups. 

What are the __dependent variables__? These are the things that you can measure or quantify in response to a change in the independent variables. They are what you predict will be different between your control and test groups based on your hypothesis.

What are your __confounding variables__? These are independent variables that you cannot control that could prevent you from collecting valid measurements. How will you minimize or eliminate these potential sources of error?

This information is summarized in the Methods section of a report. 


## Step 4. Determine which variables are relevant to the question. {-} 

Specify exactly what variables play a part in the question you are asking. For each variable, determine and explain what kind of variable each one is. [Variables are explained further here](#variables215).


## Step 5. Use the variables to state your the question in the form of a statistical null hypothesis and alternate hypothesis. {-}

The statistical hypotheses refer to your expectation of what the data will show without stating what biological processes caused those data to be different. This may be expressed as a comparison of averages between or among treatment groups, or in comparison to a hypothesized value. [The format for statistical hypotheses is explained further here](#compstatsone470). 

The statistical hypothesis and statistical tests performed usually are described near the end of a report's Methods section. 


## Step 6. Design an experiment that controls or randomizes the confounding variables. {-}

Sketch out a framework for your collected data. You already identified the variables you want to measure or collect. What will it look like in a spreadsheet? This should include everything you need as a data collection table.

What controls and replicates will you have? [(Read more about these here.)](#replicates220). What statistical tests will you use to analyze the data? [(Read more about statistics here.)](#biostats450). 

This initial design will be the starting point for writing up your Methods.


## Step 7. Conduct the experiment as planned. {-}

As you work, make notes if you do something differently than planned, or have to adjust your plan for unusual circumstances. These notes may or may not be important later as you write your Discussion.
 

## Step 8. Summarize and analyze your raw data. {-}

The data summary is the first part of your Results section. [How to summarize data is explained further here](#sumstats460).

Compare the control and test groups using the statistical test you chose earlier. This is the next part of the Results section. [How to interpret statistical tests accurately is explained further here](#compstatsone470).


## Step 9. Decide what your summarized and analyzed data mean. {-}

Think through the results of your experiment. Don’t just look at the outcome of the statistical test(s) and blindly assign a conclusion to your work. Interpret the results in light of your original biological and statistical hypotheses. This will be the first part of your Discussion section.


## Step 10. Think about how your results fit into a bigger picture. {-}

What do your results mean compared to what others have seen? What is your reasoning? This is the final part of your Discussion. [How to make arguments in the final part of your Discussion is explained further here](#discussion380).


## Practice Cases

In the Appendix there are [three sample cases that you can use to practice these steps](#overview). Each case has a general starting question, links to 1-2 open-access background articles, suggested questions to explore, and a simple raw data set. Use the case materials to practice each of the steps listed here.  
