# The Vocabulary of Experiments - Controls & Replicates {#replicates220}

## Terms That Describe Groups Within an Experiment

When we perform experiments, we want to have some confidence that the results we observe are not due to random chance, and that the observations are due to the variable we wanted to test rather than some other factor. A well-designed experiment includes appropriate __controls__ that help ensure this.

In our experience these "control" terms give more students trouble than almost any other. Part of the problem is that we use the word "control" too loosely. There are different types of control groups, but we often do not say which one we are referring to. One way to avoid confusion is to never just say "control," but rather say WHICH control group you mean.

__Control group__: A control group is one used to determine what is normal for the study organism or system. We usually use this term as part of a comparison with the treatment group. This is the generic term, and does not say clearly which type of control group we mean.

__Negative control group__: A set of samples or replicates that you KNOW should not react or give a measurable result. They provide a baseline or background for the experiment. When the experiment is using an assay of some kind, the negative control usually is a sample that has all of the components needed except one for the reaction being measured.

__Positive control group__: A set of samples or replicates that you know WILL react or give a measurable result. Positive controls provide confirmation that the methods of analysis are working correctly. When the experiment is using an assay of some kind, the positive control usually is a sample that has all of the components needed for the reaction being measured, plus a sample that is known to have the substance being measured. 

__Test, treatment, or experimental group(s)__: The group(s) that receive a treatment or experimental intervention. 


## Replicates

__Replicates__ are repeated versions of the same treatment, or repeated controls. A well-designed experiment will always have replicates. __Experimental replicates__ are independent repeats of the experimental test. __Technical replicates__ are not true replicates of the experimental group; they are repeated samples or measurements from one group. 

Imagine we are running an enzyme assay with 12 tubes. All tubes get 4 mL of buffer and substrate. Tubes 1-3 get no enzyme added, Tubes 4-6 get 1 drop of unknown enzyme solution each, Tubes 7-9 get 3 drops of unknown enzyme solution each, and Tubes 10-12 get 3 drops of a known active enzyme solution each. In this example:

|Tube #|Volume of Buffer (mL)|Volume of Substrate (mL)|Volume, Type of Enzyme|Group|
|:-:|:-:|:-:|:-:|:-:|
Tubes 1-3|4 mL|1 mL|none|Negative control
Tubes 4-6|4 mL|1 mL|1 drop each unknown enzyme sol'n|1st experimental group|
Tubes 7-9|4 mL|1 mL|3 drops each unknown enzyme sol'n|2nd experimental group|
Tubes 10-12|4 mL|1 mL|1 drop each of KNOWN enzyme, 1 unit/mL|Positive control group.  

We use a colorimeter to measure the amount of yellow product produced by enzyme activity after 10 minutes. We measure Tube 1, then 2, then 3. We then go back and measure each tube a SECOND time. Each tube was prepared separately, but following the same procedure, so we call Tubes 1-3 experimental replicates. Tubes 4-6 are experimental replicates, as are Tubes 7-9, and Tubes 10-12.

When we measure the same experimental replicate more than once, we call those measurements technical replicates. 

Technical replicates are used to make sure that we are measuring our samples accurately. The first and second measurements are not independent of each other, which is why we cannot call them experimental replicates. The three sample tubes are independent from one another, so we can call them experimental replicates. 

The difference between technical and experimental replicates will become more important when we talk about how to report summary data and perform statistical analyses.


## Terms Describing the Stage of Data Analysis

One of the common errors we see when students are starting out is they report ALL of the data points they collected. The original unfiltered or processed observations that you collect are called your __raw data__. The raw data belong in your laboratory notebook, but should not be part of your lab reports.  

__Transformed data__ are the values you obtain after applying a formula or algorithm to the raw data. Not all data are transformed; sometimes the raw observations are what are used to summarize the data. Transformed data are another kind of raw data, so are still not ready for you to put into a lab report. 

__Summary or aggregate data__ have been organized and summarized in ways that make it easier to make comparisons. Usually that means one or more summary statistics have been calculated, and/or the data have been graphed or put into a summary table. This is the type of data that should be in a report.

Here is a simple example. We want to know if hive location affects the size of worker bees. We have measured the lengths (in inches) of 10 worker honeybees each from 3 hives. One hive is in a suburban back yard, one hive is near a clover field, and one hive is near an apple orchard. 

The data shown below are raw data. Looking just at these numbers, what would you conclude?

`Yard Hive: 1.003, 0.991, 1.001, 0.991, 1.008, 0.998, 0.991, 0.993, 1.001, 0.991`

`Clover Field Hive: 1.3037, 1.288, 1.301, 1.289, 1.310, 1.298, 1.288, 1.291, 1.301, 1.288`

`Orchard Hive: 1.103, 1.090, 1.1008, 1.091, 1.109, 1.098, 1.090, 1.092, 1.101, 1.087`

The table below shows the summarized data. It is much easier to make a comparison between honeybee sizes at the three locations using the summarized data. 

|Hive Location|Mean Length (inches)|St.Dev. Length (inches)|
|:-:|:-:|:-:|
|Yard|0.997|0.006|
|Clover Field|1.296|0.008|
|Orchard|1.096|0.007|

Which type of data are easier to compare, the raw measurements or the summary data in the table?

<br/>
<hr/>

## Instructors' Supplement
### Adapting Your Guide

These are the terms that our students misuse most often when writing. Revise this page to emphasize terms that your local audience uses incorrectly most often.

