# DRAFT Scientific Writing Misconceptions

As long-time scientific writing trainers, we see many students make the same common mistakes when they first start out. Some mistakes are inevitable. It is a new genre with new expectations. Other mistakes are accidental oversights, like switching the correct word or phrase for its incorrect antonym. An example would be using the phrase "positive control group" to refer to either the "negative control group," or the "experimental treatment group." Errors like this are fairly easy to avoid, __if you make a habit of re-reading your work__ and double-checking that easily confused words are used correctly.  

Usually our students learn to avoid these sorts of mistakes quickly. What students have a harder time getting past are __misconceptions__: things they think they know about scientific writing that are not actually true.

Education research tells us that misconceptions are like any bad habit: they are much harder to break once they take hold than they are to avoid from the start. These are the most common misconceptions about scientific writing that we see, and why they are not true. We are pointing them out now BEFORE you start writing so (we hope) you can avoid them.


## Misconceptions About Vocabulary & Style

Scientists use a very specific vocabulary when we write or speak about phenomena, experiments, and data. Students can get confused and develop the misconception that using scientific terms is more important than clarity. Here is an example: 

> Bacterial transcription serves as a model for eukaryotic transcription, but is simpler in some aspects than the transcription that bacterial cells undergo.

This student author is trying to "sound scientific," but in doing so they did not catch what their sentence actually says: "Bacterial transcription is simpler than bacterial transcription." 

A similar misconception is that scientific writing needs to be padded with extra words and phrases to sound more serious. Even established, working scientists pad their writing needlessly. This example comes from the Introduction of a report:
    
>Consider the issue of distance in the process of transcription. In a situation where the distance between two transcription elements--for example, enhancers--have a large number of bases keeping them apart long distance, how does DNA support communication between these two elements, and what factors does it incorporate in order to do this? (341 chars.)

Here is the same statement, but simpler and more direct: 

> Enhancer binding sites can be widely separated on a promoter. How do proteins bound to these sites interact? What intermediate factors are needed? (146 chars.)

As you write, keep asking yourself, "is this the right word for what I mean to say?" "Do I need 10 words, or can I say this in 5 better chosen words instead?"


## Technical Errors



## Logical Errors



<br/>
<hr/>

## Instructors' Supplement

### Rationale

Reasoning, published evidence, or local data supporting a practice we recommend.


### Instructional Notes

Practical tips, tricks, or alternative ways to implement the methods or activities described. 
 
 
### Adapting Your Guide

Items that instructors should check and modify so the distributed document/web pages match their local goals or requirements. 


### Watch Out

Particularly difficult or frequent problems that we or others have encountered, and if we know any, strategies for working around them. 

