# Title and Abstract {#titles320}

Even though they are at the front of a report or article, these should be the last parts of the report that you write. You need to know what you have said in the main text before you know what to put in the abstract. Similarly, you need to know what the most important finding of your experiment is before you can write a meaningful title.


## Title

Your title should clearly communicate your topic to readers, what organisms are being studied (ideally, with scientific names), the biological property or system being studied, the particular stimulus, stress, or situation that is being applied to the system, and briefly what was found. 

At the same time your title should be clear, concise, and assertive. Imagine you have to pick an article to read and present to the class. You have looked at 30 other article titles already, and none sound appealing. You come to the last two choices. Based just on their titles, which of these 2 articles sounds like one you would want to read?

	\#31: Study of the Effects of Feline Dripomazoloid Derivative Compounds on Involuntary Caudal Motor Behavior Associated with Non-Vocal Canid Communication
	\#32: Dripomazoloids Extracted From Cat Hair Trigger Dog Tail Wagging

If your title is more than 2 typed lines, it probably is long and should be shortened.


## Abstract

The abstract is a summary of your entire report. In about 200 words or less, it should summarize the study’s main objective(s), give the scientific name of the organism you studied, and state your hypothesis. It also will summarize the study’s background, the methods, major results, and conclusions.  

You should not include references in your abstract. Any information you have in the abstract should be in the body of the text too. Citing the source of that information in the main text is sufficient. 

Even though it is usually at the front of a report or available before a presentation, the abstract should be the last part of the report that you write. You do not know what you need to summarize until the rest of the report has been written.

You can see professionally written, published [examples of some abstracts here](#paraphrasingone506).


### Examples of Poorly Written Titles & Abstracts

#### Example 1

> __Title:__ Reduced contractions of Raina pipiens’ sciatic nerve when treated with lidocaine

> __Abstract:__ The main objective of this study was to examine how the introduction of Lidocaine in the leg of a Raina pipien frog would effect the neuromuscular response. The hypothesis that we tested was if Lidocaine is used to block Na+ channels, then the voltage of the maximum contraction will decrease. We determined the twitch threshold for 3 different frog legs and then tested the frog leg at 0.1 V more than the threshold. The individual frog legs were stimulated 3 times without Lidocaine and 3 times with Lidocaine, and the separate trials for the control and treatment groups were averaged out. Our results showed that the introduction of Lidocaine does produce a smaller response when the voltage was applied as the control group had a greater response than the treatment group by an average of about .306, but we could not support our hypothesis because our p-value was not significant. The results from our two-tailed t-test gave us a p-value of .089957. We did not reject the null hypothesis because while our data shows that there is a difference when Lidocaine is injected into the frog leg, our p-value was greater than .05. Based on our results, we were not able to determine that the addition of Lidocaine into the leg of a frog does reduce the neuromuscular response when a voltage is applied.

__What Could Be Improved?__

First, the title is factually incorrect twice. The scientific name is not right, and it is the muscle to which the sciatic nerve is connected that is contracting, not the nerve. Also, how are the contractions reduced: strength, time, speed?

The first sentence of the abstract repeats the incorrect scientific name, and uses it in place of the study organism's common name.

> The main objective of this study was to examine how the introduction of Lidocaine in the leg of a Raina pipien frog would effect the neuromuscular response. 

The author also describes the force of contraction as changes in voltage, which is not accurate. This needs rewording.

> The hypothesis that we tested was if Lidocaine is used to block Na+ channels, then the voltage of the maximum contraction will decrease. 

In summarizing the results, the author does not give us any context or units for the value ".306". Is that in volts, grams, seconds?

> Our results showed that the introduction of Lidocaine does produce a smaller response when the voltage was applied as the control group had a greater response than the treatment group by an average of about .306, but we could not support our hypothesis because our p-value was not significant. 

The final part of this abstract is better. The author states clearly why they could not conclude that lidocaine reduced contraction. The one gap is that they still do not tell us what units of response they measured.

> The results from our two-tailed t-test gave us a p-value of .089957. We did not reject the null hypothesis because while our data shows that there is a difference when Lidocaine is injected into the frog leg, our p-value was greater than .05. Based on our results, we were not able to determine that the addition of Lidocaine into the leg of a frog does reduce the neuromuscular response when a voltage is applied.

To see how this might be revised, take a look at the first example in the next section. It is the same author's title and abstract on their revised version of the report.

<br>

#### Example 2

> __Title:__ The Physiological Impacts of Insect Growth Hormones

> __Abstract:__ Research in the insect growth continuous to bring notice in discussion regarding insect protection considering their value in the ecosystem. With intense curiosity to find better ways to alter the physiology of insects, without the need of pesticides, lab continues to occur to decrease their harmful ability. Here, this lab experiments the effects of insect growth hormones on how they might affect the Manduca sexta. The expectation or hypothesis of the lab is that if the Manduca sexta is treated with the IGR levels in its diet, it will not grow normally as the control group. While the observations showed some differences, our data calculation showed that there was no difference or impact by the hormones; hence the differences might have been by chance. The Control and Treatment grew relatively at the same rate until the control caterpillar started their metamorphosis while the treatment continued to grow as larvae. With more experiments, more knowledge can be discovered.

__What Could Be Improved?__

This title is very generic and vague. There are several insect growth hormones affecting dozens of pathways and systems. Saying the study is in insects is not enough: 1 in 4 species of animals on Earth is an insect. We have no idea what to look for in this article.

The abstract begins with two sentences that are not needed. They do not describe the study, and are not setting the reader up to understand the study. 

> Research in the insect growth continuous to bring notice in discussion regarding insect protection considering their value in the ecosystem. With intense curiosity to find better ways to alter the physiology of insects, without the need of pesticides, lab continues to occur to decrease their harmful ability. 

Like the title, the summary of the experiment is too broad. The only improvement here is we know what species the authored studied.

> Here, this lab experiments the effects of insect growth hormones on how they might affect the Manduca sexta. 

This next sentence is not grammatically correct, and does not explain what IGR is. The hypothesis is not clear. 

> The expectation is that Manduca sexta treated with the IGR levels in its diet, it will not grow normally as the control group. 

The next sentence provides no specifics about what their data showed.

> While the observations showed some differences, our data calculation showed that there was no difference or impact by the hormones; hence the differences might have been by chance. 

This sentence really should come before the preceding one.  

> The Control and Treatment grew relatively at the same rate until the control caterpillar started their metamorphosis while the treatment continued to grow as larvae.

This is entirely unnecessary.

> With more experiments, more knowledge can be discovered.

<br>

#### Example 3

> __Title:__ Effects of Soil Temperature on the Phenotypic plasticity and Energy Allocation of Beans

> __Abstract:__ Phenotypic plasticity, coupled with energy allocation, is a key mechanism for plants to cope with environmental stress. With a given amount of resources, plants tend to allocate the acquired resources toward body parts, which can obtain further bioavailable resources, and reduce the growth and biomass of parts that are more energy-consuming/ inefficient. This report implemented an allometric approach to study how the soil temperature influences the phenotypic changes of Vigna radiata (mung beans). Results show no statistically significant difference (two-sample t-test p-value < 0.05) in all, except weights of whole plant, body size comparisons. Therefore, our hypothesis (higher soil temperature leads to higher root-to-shoot weight/length ratio) was not supported. The effects of phenotypic plasticity and allocation strategies of _V. radiata_ are discussed with further suggestions on ways to improve the experimental design to be closer to real-life conditions.

__What Could Be Improved?__

This title is better in it makes it clear what organisms are being studied (although the scientific name is missing), and the particular stimulus. Still missing: what is it about plasticity and energy allocation that is being assessed? 

In the abstract, the author spent too much time trying to sound important. These two sentences are not really needed. 

> Phenotypic plasticity, coupled with energy allocation, is a key mechanism for plants to cope with environmental stress. With a given amount of resources, plants tend to allocate the acquired resources toward body parts, which can obtain further bioavailable resources, and reduce the growth and biomass of parts that are more energy-consuming/ inefficient. 

This sentence does not tell us anything more about __what__ phenotypic changes were assessed.

> This report implemented an allometric approach to study how the soil temperature influences the phenotypic changes of Vigna radiata (mung beans). 

Read this sentence carefully. Is the author saying that there is a difference in weights of whole plants, of sizes (and how was that measured), or both? What are the comparison groups? Or, is the author saying what statistical test they used and what alpha value they applied?

> Results show no statistically significant difference (two-sample t-test p-value < 0.05) in all, except weights of whole plant, body size comparisons. 

We have to get down to here to see what the author was measuring.

> Therefore, our hypothesis (higher soil temperature leads to higher root-to-shoot weight/length ratio) was not supported. 

This sounds excessive. Is it really needed?

> The effects of phenotypic plasticity and allocation strategies of _V. radiata_ are discussed with further suggestions on ways to improve the experimental design to be closer to real-life conditions.

<br>

### Examples of Well-Written Titles & Abstracts

#### Example 1

> __Title:__ Reduced contractions of _Rana pipiens_’ gastrocnemius muscle when treated with lidocaine

> __Abstract:__ The objective of this study was to see how introducing the Na+ channel blocker Lidocaine into the leg of a grass frog _(Rana pipiens)_ would effect the neuromuscular response. The hypothesis that we tested was if Lidocaine blocks Na+ channels, then the force generated at maximum contraction (as measured by voltage from a force transducer) will decrease. We determined the twitch threshold for 3 different frog legs and then tested the frog leg at a stimulation voltage of 0.1 V more than the threshold. Individual frog legs were stimulated 3 times without Lidocaine and 3 times with Lidocaine, and the separate trials for the control and treatment groups were averaged. Graphed summary results showed the introduction of Lidocaine did produce a smaller response when the voltage was applied, supporting our hypothesis. However the results from our one-tailed t-test gave us a p-value of 0.089957, so we could not reject the null hypothesis. Based on our results, we were not able to say that the addition of Lidocaine into the leg of a frog reduces the maximum contraction when a stimulus voltage is applied.

__What Is Particularly Good?__ 

This is the revised title and abstract submitted by the same student as in Example 1 in the previous section. 

1. The title is short, but also makes it clear what the topic, model system, and intervention are. 
2. The key finding is clear. 
3. The abstract now describes the study organism, question, and how the data were collected more accurately. 

<br>

#### Example 2

> __Title:__ Lower Water Temperature Reduces the Frequency of Agonistic Display Behaviors in Betta Fish, _Betta splendens_

> __Abstract:__ In order to understand behaviors in animals, specifically behaviors that require a high energy expenditure, it is important to understand their metabolism and the factors that affect it. Heterothermic metabolism is directly dependent on temperature, meaning that as temperature decreases, metabolism also decreases. In order to study the effects of decreased metabolism, we studied aggressive behavior, a high energy behavior, in _Betta splendens_. It was hypothesized that if the betta fish had a reduced metabolism in colder water, they would display aggressive behaviors less frequently. As predicted, the betta fish displayed significantly less aggressive behavior, measured by time spent displaying a red mane, when they were in cold water than when they were in room temperature water. Future studies should examine various fish species that live in various temperatures to see if the fish have adapted their metabolism for different environments. 

__What Is Particularly Good?__ 

1. The title makes it clear that this is a study of intra-specific behaviors in fish, and that the variable tested is environmental temperature.
2. The abstract begins with a general statement that helps the reader put this particular study in a much larger context. 
3. The rationale for the study is clear, along with why they used betta fish. 
4. Their experimental measures and outcomes are summarized clearly. 
5. Their suggestions for future study focus specifically on extending their particular study; the author does not try to stretch their findings too far. 

This abstract does have one thin spot. The author could have given a one sentence outline of the conditions in which they did their study, and how they determined that their observations changed significantly with water temperature. 

<br>

#### Example 3

> __Title:__ Determining the Optimal Growing Temperature Range for Spinach _(Spinacia oleracea)_ Based on Redox Activity in Photosystem II

> __Abstract:__ The purpose of this experiment was to determine whether the optimal temperature range at which spinach _(Spinacia oleracea)_ grows is similar to the temperature at which spinach chloroplasts perform photosynthesis best. In order to determine this optimal temperature range, PSII activity was measured using the Hill reaction and DCIP as the alternative electron acceptor. Isolated chloroplasts in Hill assay buffer were incubated at 5 temperatures for 10 minutes: 0°C, 12°C, 25°C, 35°C, and 60°C.Then DCIP was added and absorbances were measured at time zero, then after 10, 20, and 30 minutes of incubation. Average rates of change in absorbance between 0 and 10 minutes, 10 and 20 minutes, and 20 and 30 minutes were compared using an ANOVA statistical test. Individual groups were compared using Tukey's post-hoc test. From the statistical analysis, the optimal temperature range for PSII activity was determined to be between 12°C and 35°C. This is a wider range than the published optimum growth temperature range for spinach plants of 10°to 15°C. Proposed reasons for decreased activity at low (0°C) and high (60°C) temperatures include alterations in the chloroplast membrane, electron carrier and acceptors, or essential proteins associated with PSII. 

__What Is Particularly Good?__ 

1. The title makes it clear what the author wants to compare their results to, the question they are asking, how they are testing it, and the target species. 
2. Some of what makes this a good abstract is what is NOT in it. 
    + The abstract does NOT have a citation for the optimum growing range of spinach. That information was cited in the main text, and did not need to be repeated in the abstract. 
    + The basic methods, statistical analysis, and main outcomes are all described clearly and __concisely__; there are no extra details included.
    + The comparison between temperature range for PS-II activity and plant growth is summarized, but detailed discussion of that point has been left to the main text. 
