# Introduction {#introduction340}

The introduction tells the reader what topic you are addressing, presents the current state of knowledge of this topic, and ties prior knowledge and background information to your biological question. 

The written version begins with a brief general introduction to the subject or problem, then moves on to more specific information that relates to your hypothesis. It will explain the underlying biological principles a reader needs to know to understand the purpose of the experiment. 

These are the questions your should try to answer in the Introduction.

1. What do we already know about this particular organism, biochemical system, or experimental model? 
2. What questions come to mind when we think about this system? In other words, what is the biological question we might ask, or current unknowns we might explore? (Getting more specific.)
3. What question are __you__ focusing on? Why are you asking this question? What do we need to know to answer it? (Still more specific.)
4. What model system are you using? Why?
5. What do you expect to happen in this model system? Why are you predicting this will happen? (This last item is your hypothesis. Be sure you state it clearly, and that it is a __testable__ hypothesis.) 


## Other Important Features, Tips

The Introduction should make it clear what your dependent and independent variables are. You can either say this as part of the hypothesis or explain it as part of the overall purpose of the experiment.

The Introduction should always include the scientific name of any study organisms (in _italics_, with first letter of the genus capitalized and the rest of the name in lower case). If you are not using an intact organism, always say what model system you are using. Include a brief (1-2 sentences) explanation for why the model organism or system is a good choice for your experiment.

Sources for all information that is not common knowledge need to be referenced using the (Name, Year) citation format ([described further here](#citformats510)). Use primary literature whenever possible, and avoid secondary literature unless that is the only source you can find; do not use non-scientific literature at all. If you are unsure whether or not a source is an appropriate one, ask your instructor.

Often we see students try to find supporting sources that describe their exact same experiment. __Don’t try to find an experiment just like yours__. You do not need a source to prove you “did the experiment right.” The goal of doing and reporting experiments is to widen our knowledge of the world around us. We use what others have published as a starting point for asking new questions. There is a very practical reason not to do this too. If you sent a paper out for review that is nearly identical to another scientist’s work, the editor of the journal will immediately return it with a rejection letter saying that you have not made any significant contribution to that particular field. 


## Examples of Poorly Written Introduction Sections

### Example 1

The background information in this example is so general that we cannot see how it connects to the specific experiment they did. 

> The test subject of this experiment is _Manduca sexta_, an insect in the order Lepidoptera. These organisms undergo a holometabolous life cycle consisting of egg, larvae, pupa, and adult stages. There is a major body reorganization during pupal metamorphosis (Johnson, 2018). All insects and vertebrates control growth, development, and behavior using hormone and neuron signaling. Hormones are received by the brain as inputs, the brain then sends output signals to different organs or tissues in the body to create a response. Insect growth regulators (IGRs) can be used to disrupt processes of development regulated by insect hormones. IGRs often mimic Juvenile Hormone in order to stop the life cycle from progressing (Staal, 1975). This experiment used Gentrol, an IGR that contains a mimic of Juvenile Hormone to prevent development. It was hypothesized that if _Manduca sexta_ are treated with Gentrol, the individuals will experience inhibited growth in length and mass compared to a control group treated with DI water. 

Look at this sentence; can you as a reader tell what they are interested in exploring, other than growth, development or behavior? 

> All insects and vertebrates control growth, development, and behavior using hormone and neuron signaling. Hormones are received by the brain as inputs, the brain then sends output signals to different organs or tissues in the body to create a response.

The preceding two sentences could be more concise, and focus attention on insects specifically.

<br>

### Example 2

This example contains a lot of unnecessary extra detail, and many factual errors.The author does not get to the point of what their experiment is about until the last few sentences. 

> All living organisms must produce energy in order to survive. In plants this form of energy is adenosine triphosphate (ATP), which is produced in the organism’s chloroplasts and mitochondria. During the daytime ATP is synthesized in the thylakoid membrane of the chloroplasts, where electrons in an antenna complex are excited by ultraviolet rays from the sun. This energy is passed around the antenna complex until it reaches the special pair, which holds its electrons at a lower energy level than the other electrons in the antenna complex. This effectively traps the energy in the reaction center. The excited electrons are then passed on to an electron carrier. In photosystem II, Q accepts the electrons and passes them on to the cytochrome b6f complex, which pumps protons into the thylakoid space. An ATP synthase uses the electrical chemical gradient produced by the pumping of protons into the thylakoid space to bring protons back across the thylakoid membrane and synthesize ATP. In photosystem I ferredoxin accepts the electrons and passes them on to FNR. FNR then uses these electrons to synthesize NADPH. The electrons in photosystem II are replenished by water, which causes them to give off oxygen as a waste product. The photosystem I electrons are replenished by those from photosystem II.

>It is possible to measure the overall activity of chloroplasts. Specifically, one can measure the activity of photosystem II using the hill reaction. In this reaction an alternate electron acceptor receives the electrons from the photosystem. One example of an alternative electron acceptor is DCIP, which transforms from dark blue to colorless as it is reduced. Therefore, one can measure photosystem II activity by measuring the absorbance when DCIP is used an electron acceptor. Chloroplasts activity is known to be affected by various external factors. In his study on factors that affect chloroplasts activity in cotton plants, Kenneth Fry identified light intensity, light duration, pH buffer presence, and temperature as external factors that can have an effect on chloroplast activity (Fry, 1970). One can observe how these specific factors influence chloroplast activity by using the hill reaction. 

> It is important to understand how external factors such as temperature affect chloroplast activity, because optimal conditions must be utilized in order to maximize crop production in the agriculture industry. In order to better understand how different temperatures impact chloroplast activity in _Spinacia oleracea_, we decided to record the absorbances of samples containing chloroplasts and DCIP over a thirty minute period. We seperated twelve spinach chloroplast samples into four groups of three and exposed each group to a different temperature level. The four temperature levels that we used were 0°C, room temperature (23°C), 40°C, and 55°C. We hypothesize that there will be a statistically significant difference in chloroplast activity between the samples exposed to room temperature water and those exposed to 0°C, 40°C, and 55°C, with the samples exposed to room temperature water showing more chloroplast activity. 

The first two paragraphs can be reduced to 1-2 sentences at most. Paragraph 3 is the relevant background, and it needs to be supported with primary literature. 

<br>

### Example 3

This next example is the full Introduction section from the report. What is missing? 

> The muscular system cannot work without its connection to the nervous system, as the nervous system generates an action potential that serves as a stimulus for muscular movement. The neuromuscular functioning has a level of specificity to where it can target individual areas of the body for movement, unlike the endocrine system that distributes hormones into the blood for transport. As an action potential is generated through the nervous system, it continues along the Nodes of Ranvier of a neuron’s axon in order for the excitation to travel to the muscle. This stimulates contractions, a process assisted by insulating myelin sheath on the axon (Tasaki, 1952). Contractions that form as a result of the action potential can be recorded on myograms to evaluate the amplitude and force of a contraction. The force that is generated is dependent on the energy created through changing concentrations of sodium and potassium, which determine if threshold potentials are reached. Sodium channels allow charge carries to move across a membrane, depolarizing the cells, and promoting the driving of an action potential beyond its threshold value (Starmer, 2003). Contractions are relatively easy to see in a frog leg, as the separation of the gastrocnemius muscle from the rest of the leg is a simple process. This muscle is also very important to the organism with its providing of significant strength, since frogs move using jumping movements generated by the legs. 

There is no description of the experimental goals or the hypothesis, and no predictions. This would be marked "Unacceptable" using our bins grading criteria.

<br>

### Example 4

What do you see here?

> Photosynthesis is the multi-step process through which plants capture and store energy. Electrons are energized by rays of sunlight, therefore starting a chain of energy transfer reactions in which energy is carried in the form of high energy electron carriers (Nelson & Yocum, 2006). As oxidation/reduction reactions, or redox reactions, involve the transfer of electrons from one species to another, this process is very important to the process of photosynthesis. The rate of oxidation is therefore indicative of the rate of photosynthesis (Antal et al.: 2012). This oxidation is normally carried out by plastoquinone, a high energy electron carrier that is difficult to track the change in relative concentrations in oxidized and reduced substance over time (Nelson & Yocum, 2006). Therefore, in order to measure this redox change in order to determine photosynthetic rate experimentally, a different electron carrier reducible substance must be used. DCIP is used as such a substance to measure photosynthetic electron transport, as the rate of reduction can be measured by changes in absorbance through UV-vis spectroscopy (Antal et al.: 2012). This makes it a useful tool in studies involving photosynthesis, the topic of interest of this paper. 

> Several studies have investigated the effects of temperature on photosynthesis, with varying plant species and varying temperature ranges (Rosinger, Wilson, & Kerr, 1982). Studies done in Prague also measured the rate of photosystem I, using oxygen evolution rather than the Hill Assay as their means of measuring progress, and found that at lower temperatures this evolution, and therefore the rate of reaction, were low, and that they steadily increased with temperature (Lukeš, Procházková, Shmidt, Nedbalová, & Kaftan: 2014). It has been conjectured that this influence by temperature is due to the fact that this is a membrane reaction, and that temperature change may alter the conditions and flexibility of these membranes (Rosinger et al.: 1982). In relation to this, differing studies have found differing results and relationships with temperature for different species, specifically in response to chilling. Researchers believe this could be indicative of some plants being more “chill-sensitive” or “chill-resistant” than others (Rosinger et al.: 1982). In the opposite direction of temperature change, different studies have also found different results when measuring the activity of photosynthesis when the system is heated. While heat does seem to fairly consistently have a positive correlation with activity, in that increasing the heat also increases the activity of photosynthesis, studies have shown there is an upper limit to this phenomena (Nolan & Smillie: 1976). Studies done by Nolan and Smillie demonstrate that after the peak of activity, there comes a rapid decrease, at which point soon after activity shuts down completely. This indicates that at a certain point the increase in temperature is actually harmful and breaks down essential components of the system, which has a counterproductive effect on increasing the rate. Similarly to the studies on chilling done by Rosinger, these studies also showed that this upper limit was different for different plant species.

> Therefore, for this report, previous research was combined on the temperature dependence of photosynthesis and the Hill Assay in order to design an experiment which tested the effects of extreme temperatures on the rate of photosystem I of chloroplasts isolated from spinach leaves. As temperatures on both the side of heating and cooling were taken to more extreme limits, we predicted that both reactions would demonstrate a decrease in photosynthetic activity, as compared to the samples run at room temperature.

This Introduction is far too long. In fact the GTA grading it suspected it might be plagiarized because it was so long, had so much more information than was needed, and used language that was more detailed than how the experiment had been discussed in class.

<br>

### Example 5

This Introduction reads more like part of the Discussion section. It focuses on the problems in the experiment, not the original idea being studied. 

> Nitrogen is present in the soil in most areas, and the absence or presence of nitrogen can play a role in the growth of the plant. In the case of the field pea, we will be looking to see if the absence or presence of nitrogen plays a positive or negative role in the growth of our field peas. While we were not the specific group that planted and cared for these plants, we did measure the data ourselves and recorded the length for both the roots and shoots of the control and experimental group. Our original experimental design ended up being mixed up with other plants, and was lost after the two weeks of caring for the plants was over. Another group was kind enough to let us use their experimental design in order to be able to record data. We used their experimental design but obtained our own data  

<br>

### Example 6

This Introduction section reads well and is informative, but still would earn a score of "Unacceptable" for the report overall. Do you see why?

> The Rhizobia bacterium is a diazotroph. This means that it can take nitrogen from the air and turn it into a form that is useful to plants and other organisms. This conversion of nitrogen in air to a usable form of nitrogen is known as nitrogen fixation\*. If soil does not contain the needed amount of nitrogen, then the plants will die or try to find more within the soil. This searching for nitrogen within the soil causes the plant to grow longer roots which means that the shoots of the plant will be shorter. This process is known as plant allocation. This means that a plant will take resources from one location within the plant and put it into another to gain access to hard to reach resources\*. Legumes such as alfalfa _(Medicago sativa)_ benefit from nitrogen fixation by Rhizobium. The bacterium relies on the alfalfa plant to produce needed amino acids that it uses for energy\*. The Rhizobia bacterium forms nodules on the roots of the plant. This symbiotic relationship benefits both organisms and neither one is harmed\*. In the lab, we tested this relationship between rhizobia and alfalfa by examining how the plants allocated resources for growth in the presence or absence of the rhizobia bacteria. Our hypothesis is that due to this symbiotic relationship and considering plant allocation, that the shoots of the alfalfa with the rhizobium bacteria will be longer than those of the alfalfa without the bacterium. 

One of our basic criteria for lab reports is that they put the experiment in the context of primary literature. Each of the asterisks in the text marks a statement that needs to be supported by a primary literature citation. We would not expect every one to have a citation, but at least some need to have a source. Also, the Introduction does not reference the results any other prior experiments by others. 

<br>

## Examples of Well-Written Introduction Sections

### Example 1

> In photosynthesis, plants use sunlight, water, and CO<sub>2</sub> to generate 6-carbon glucose molecules that store energy and fixed carbon for the organism.The molecule complexes that perform photosynthesis in plants are affected by changes in temperature. At too high of temperatures, many proteins are denatured and do not work correctly. At low temperatures, the proteins may slow activity until they are unable to work properly. At extremely low temperatures, plants have been found to undergo photoinhibition, and PSII loses its ability to function at all (Briantais, et. al: 1992). Studies have found that cold does not greatly affect photosynthesis by spinach _(Spinacia oleracea)_ and does not trigger plant stress (Boese and Huner: 1990). On the other hand, at high temperatures, electron transport slows in PSII, lowering photosynthesis in most plants (Enami, et. al: 1994). Spinach has been shown to respond to high temperatures with complete shutdown of photosystem II and undergoing photoinactivation (Yamane, et. al, 1998). This suggests spinach's photosystem II operates best at a lower range of temperatures than crops like beans. This experiment aims to compare the ideal temperature range for chloroplasts from spinach versus bean leaves to perform photosynthesis. We hypothesize that the optimal temperature for photosystem II activity will be lower in spinach than beans. 

__What Is Particularly Good?__ 

1. It is clear that this author's experiment is based on prior literature, and that the experimental approach aims to extend those studies. 
2. There is a clear line of thinking leading to the experimental question, and there is a clear hypothesis-based prediction. 

<br>

### Example 2

> The neuromuscular system consists of the interworking of neurons and muscles to respond to stimuli with muscular contractions. Skeletal muscles consist of many myofibers which are multinuclear, cylindrical cells. They are innervated and activated by motor neurons. When nerve impulses arrive at the neuromuscular junction, acetylcholine is released from the presynaptic nerve terminal. This process results in the release of Ca<sup>2+</sup> from its storage site in the sarcoplasmic reticulum which initiates the contraction of muscle fibers, causing them to shorten (Johnson, 2018). So how does muscle contraction change when more Ca<sup>2+</sup> than normal is released? Weber and Herz (2017) investigated the influence of caffeine on contraction of the thigh muscle in a grass frog _(Rana pipiens)_ and found that, with increasing concentrations of caffeine, there was an immediate release of Ca<sup>2+</sup> and a more intense muscle contraction when the corresponding nerve was stimulated. In a similar experiment, researchers manipulated the gastrocnemius muscle of the grass frog by introducing caffeine and observing the effects on different stages of muscle contraction (Tallis & Wilson, 2015). The grass frog is a good subject for these studies because the neuromuscular system in their leg is easy to access, and the force generated is easy to measure. 

> Other studies have shown that caffeine promotes skeletal muscle contraction by inhibiting Ca<sup>2+</sup> ion reuptake into the sarcoplasmic reticulum. Slowing down reuptake increases the time required for the relaxation phase of a muscle twitch (Tallis & Wilson, 2015). Our question is, does releasing more Ca<sup>2+</sup> initially do the same thing? We hypothesized that increasing the concentration of Ca<sup>2+</sup> ions before initiating a contraction will trigger a stronger contraction too, but will shorten the latency time between a stimulus and the start of a contraction.  We tested this by comparing latency, contractile time and force, and relaxation time of frog gastrocnemius muscles treated with caffeine or with A23187, which inserts in the SR membrane and releases extra Ca<sup>2+</sup> ions. 

__What Is Particularly Good?__ 

1. Again, it is clear that this author's experiment is based on prior literature, and that the experimental approach aims to extend those studies. 
2. There is a clear line of thinking leading to the experimental question, and there is a clear hypothesis-based prediction. 
3. The cited sources are more recent. 

