# Methods

The Methods give readers a general idea of procedures you used to test your hypothesis. 

These are the questions your should try to answer in this section.

1. Briefly, how did you do your experiment? What are the essential details that someone else would need to know to repeat it?
2. If appropriate, where and how were the organisms collected and maintained? If you used materials extracted or obtained from organisms, what was the source?
3. If you used an unusual method to create the independent variable, describe how you did it. If you used commonly available methods, state them without explanation. 
4. What volume and concentration of key reagents (drugs added, volumes injected, etc.) were used in the experiment?
5. What statistical tests did you use? What groups were compared? 


## Be Careful With Details

Many of our students writing their first lab report have trouble writing this section. It is hard to judge how much information is needed. There should be enough detailed information provided so that someone not directly involved in the project (but works in a lab setting) could repeat the experiments. 

At the same time, we do not want them to just recopy the lab manual or protocol or add useless details. Examples of TOO much detail are "...I used a paint brush to place a red dot on each grasshopper..." or "...we graphed all twelve of our data points on an X-Y graph..."

You want to summarize your methods, use diagrams, and find other ways to make your reader understand how you did your studies. Look at articles you have read; what did they keep or leave out?


## Other Tips

The Methods section describes something you already did in the past, so should be written in past tense. Usually it is written without saying "we" or "I", although this is becoming less important in some fields. 

Usually the methods you use are well established so you do not need to cite a source for the procedures. The exception is if you change a well-known method because of something another study found or reported; in this case it is appropriate to cite the source for the facts that made you change your methods from what is done normally.


## Examples of Poorly Written Methods Sections

### Overly Detailed
This particular example reads just like the laboratory manual, and in fact was copied. So it is both poorly written Methods section AND plagiarized.

1. Briefly, how did you do your experiment? What are the essential details that someone else would need to know to repeat it?


### Missing Essential Information

2. If appropriate, where and how were the organisms collected and maintained? If you used materials extracted or obtained from organisms, what was the source?
3. If you used an unusual method to create the independent variable, describe how you did it. If you used commonly available methods, state them without explanation. 
4. What volume and concentration of key reagents (drugs added, volumes injected, etc.) were used in the experiment?
5. What statistical tests did you use? What groups were compared? 


### Poorly Organized


## Examples of Well-Written Methods Sections





