# Results {#results360}

The Results section is where you report your observations and findings. You also summarize and organize your findings (especially numbers) so they are easier to understand. These are the questions your should try to answer in the Results.

1. Where are your data summarized? What tables and figures contain which parts of your data?
2. What __general__ trends did you see? Did specific trials or runs within the larger experiment come out differently? If so, how were they different?
3. If you tested more than one group (or had test and control groups) are they statistically different from one another? How much?


## Other Tips

* Usually the Results section is the shortest part of a lab report. Often this section will be just a few sentences that refer the readers to the data figures.
* Do not repeat details you already provided in the Materials and Methods. 
* NEVER include raw data. Only report the summarized data.
* Do not try to interpret or discuss your data.  Only state what your results __were__, not what they might __mean__.


## Examples of Poorly Written Results Sections

### Example 1

This results section needs significant revision.

> We saw in Figure 1 that the highest length that the control group reached was 8.29 cm, which was caterpillar number 8, and the lowest one was 3.88 cm, which was caterpillar number 2. The highest length that the treatment group reached was 8.87 cm, which was caterpillar number 11, and the lowest length was 3.80, which it was caterpillar number 2. In figure 2, the highest weight that the control group reached was 11.165 g, which was number 8, and the lowest weight they reached was 5.92 g, which was caterpillar number 5. For the treatment group, the highest was 11.177 g, which was caterpillar number 12 and the lowest was 0.725 g, which was caterpillar number 2. After running the one-tailed two-sample t-test, we determined that it was insignificant because the p-value was higher than 0.05. we received 0.48 p-value for the length and 0.49 p-value of the weight. 

1. They are describing raw data, not summarized data. While it is not shown here, Figures 1 and 2 only showed their raw data as well.
2. There is no description of the general trends in the data. 
3. There are no summary statistics, and the results of the t-test are reported incorrectly.

<br>

### Example 2

This results section has several problems.

> The mean twitch threshold for the control trials of the three legs was 0.18 V and for the experimental trials the mean twitch threshold was 0.16 V. The standard deviation or the control trials was 0.09 V and the standard deviation for the experimental trials was 0.04 V. We used a one-tailed paired t-test to analyze our results. The mean twitch threshold of the experimental trials did not show a statistically significant difference from than that of the control trials. There did not appear to be any differences in the amount of movement at the twitch threshold between each trial, and all frog legs remained intact throughout the experiment. 

1. Where are the references to tables and figures? Where are their data summarized?
2. The summary statistics and statistical comparison analysis are not reported correctly.
3. What is the meaning of this phrase? "There did not appear to be any differences in the amount of movement at the twitch threshold between each trial..."
4. Why is this phrase included? "...and all frog legs remained intact throughout the experiment."

<br>

### Example 3

This results section has a serious flaw, though it might not be obvious at first.

> Throughout the experiment, both groups of caterpillars were observed to grow at about the same rate. Both groups were equally as mobile and both ate about the same amount of food; when food was replaced, it very often was replaced for all six caterpillars at once. The two sample t-test demonstrated a lack of statistical difference between the treatment group and the control group means shown in Figure 1 (t-stat = 0.022, df = 3, P = 0.98). 
>
> It is important to note that one of the caterpillars in the control group failed to grow more than 0.2 grams during the two weeks. Although it remained alive for about a week and a half, it finally died. Because this caterpillar performed drastically different than the control is expected to, it was considered an outlier and not factored into the data. Had the caterpillar been included, the data would have shown that Precor in fact accelerated _M. sexta_ growth. The failure of this caterpillar to grow would have skewed the results and created the illusion that the average growth of _M. sexta_ larvae without any external stressor or stimulus  was far slower than it was. 

This results section combines results and interpretation; the latter (which is basically all of the second paragraph) belongs in the discussion.

<br>

### Example 4

The text below is the __entire__ text of the results section for one author's report.

> Figure 1: Summary of data of measured absorbances, and the percent increase in these absorbances over time. These numbers are shown as individual data points and as averages for each group.
>
> Figure 2: Graph displaying the average of percent change in absorbances over time for each group, at 10, 20, and 30 minutes respectively.
>
> Figure 3: Summary of statistical tests of a Mixed Design ANOVA, determining significant difference between the three groups in temperature groups, in percent change over time and interaction between percent change and temperature. This test demonstrates there is a statistical significance to these differences.
>
> Figure 4: This figure demonstrates a Tukey’s Honestly Significant Difference Test, which checks for statistical difference between each group specifically. This demonstrates that there was statistical significance in the difference between the heated group and both other groups, but not between the two other groups themselves, those being the room temperature and chilled groups.

This example illustrates two problems that we do not see very often, but often enough to warrant pointing them out. 

1. The results section should __refer__ to the figures, but figure legends are not the same as the results. They are a separate part of a report.
2. Figures 3 and 4 refer to two statistical tests incorrectly. Always be sure to use the correct terminology for the data, statistical tests, etc.

<br>

## Examples of Well-Written Results Sections

### Example 1

> Comparisons of root:shoot weight ratios for control and salt water treated plants are summarized in Figure 1. Root:shoot weight ratios for the salt water plants (6.31±0.927, mean±s.d.) were significantly higher than those of the tap water plants (3.18±0.148) (t-stat = 3.89, df = 10, p = 0.00152). Comparisons of root:shoot length ratios are summarized in Figure 2. Salt water treated plants had significantly shorter shoots compared to roots than tap water treated plants (5.13±1.46 vs. 17.8±2.94) (t-stat = 9.44, df = 10, p = 0.00000134). There were no notable outlier data points.

__What Is Particularly Good?__ 

1. This author points the reader to their figures, and provides a compact summary of their results. 
2. Nothing has been included that is not needed. 
3. They do not interpret their results, just report them. 

<br>

### Example 2

> Figure 1 shows the average change in DCIP absorbance over time in the presence of chloroplasts from green vs purple lettuce leaves. Overall the results of the experiment showed similar patterns of change in absorbance for green and purple chloroplast samples over the 30-minute period. In Figure 1, average % change overlapped during each 10 minute period, and total change in absorbance at 30 minutes was about the same for samples with chloroplasts from green vs purple leaves. The results of the two sample T-test showed that there was no significant difference between the percent change in absorbance from T0 to T30 for purple and green lettuce (t=0.074, df=4, p=0.944). The color of the lettuce leaf had little effect on change in absorbance over time.

__What Is Particularly Good?__ 

1. This results section does not provide as much detail as the first example, but it still makes it clear what the central observation is. 
2. The statistics are reported correctly. 
3. The author makes a conclusion statement about their data, but does not go on to interpret the meaning of the data in a larger context. 

