# (PART) Summarizing and Analyzing Data {-}
# Reporting Your Data {#datatypes400}

Part 4 of this Guide shows you how to summarize, analyze, then present data that you collect during your experiments. This page provides a general overview; other pages provide more specific instructions, and links to additional resources.

We describe summarizing and analyzing your data as separate steps in the writing process. In practice though, you probably will be working on both at the same time. 


## How Should You Report Your Results?

Results of an experiment can be summarized and reported several ways. Which method you should use depends on what kind of data you are trying to share with readers, and what you want readers to understand or see.

Generally we lump photos, diagrams, and illustrations with data graphs, charts, and other visual data summaries under the umbrella name of __figures__. Usually you present your results in the form of a table or a figure, but not both. The only time it is appropriate to present the same data twice in different forms is when the data need to be interpreted more than one way. This is not something you usually need to do in student lab reports though.

Imagine you did an experiment to determine the minimum and maximum amount of 6 different B–vitamins that fence lizards must consume each day to maintain healthy scale shape and color. What kinds of data would you collect, and how might you report the results in an article?  

It is unlikely that your readers know what fence lizard scales look like close up, let alone the normal color and shape of the scales. In this situation you could use __photographs__ to report visual observations that are not easily quantified, or when it is useful for readers to see for themselves what you observed. You might choose two photos; one showing healthy scales and another showing deformed, poorly colored scales. Now your readers have some context for the other data you will present. [How to use photos and illustrations effectively is explained further here.](#photos430)

You observe that the color of the scales is normal as long as the __ratio__ of B1 to B6 in the lizards' diet is 1:10. Lizards with a diet containing 10 mg B1 and 100 mg B6 have normally shaped gray scales. Lizards eating a diet that is deficient in both vitamins (say, averaging 1 mg B1 and 10 mg B6) develop deformed scales but the scales are still gray. If their diet changes so it has 10 mg B1 and 10 mg B6, the lizards' scales turn tan or brown. For this observation, the relative levels of vitamins are more important for the reader to see. When your readers need to see ratios, trends or changes over time, a __data graph or chart__ usually is the best way to summarize and report your results. [How to create data graphs and charts is explained here.](#chartsone425)

Suppose you observe instead that the relative amounts of B1 compared to B6 is not that important; it is the absolute quantity (i.e., 10 mg B1, and 100 mg B6) of each vitamin that determines whether the scales have the correct shape and color. Now your readers need to know the specific numbers, so a __data summary table__ would be the better choice to report your results. [How to put together data tables is explained here.](#tables435)


## How to Number Tables and Figures in Your Reports

Figures and tables are numbered separately, in the order they are referred to in your text. Do not mix the table and figure numbers; keep them separate. For example, imagine you wrote a lab report containing 2 summary tables and three graphs. In the main text you refer to the first table, then two of the figures, then the second table, and finally, the third figure. You would number the tables and figures as:

* Table 1
* Figure 1
* Figure 2
* Table 2
* Figure 3

You MUST reference each table and figure in the main text of your lab report. If you do not reference each table or figure, readers do not know where to look for the data you are using to support your claims. 


## Where to Put the Tables, Figures, and Legends

Table and figures are placed at the end of a lab report, after the Literature Cited, starting on a new page. Tables come first, and should be inserted in numerical order, with the legends directly below their corresponding table. Next come the figures, again in numerical order, with the legends directly beneath the corresponding figure.

> __Tidbit__: You might wonder why tables and figures are put at the end rather than being inserted into the text. It is a holdover from the time before online electronic submission. Up to the mid-1990s, authors sent 3-5 hard copies of their manuscript to a journal editor for review. Tables and figures were placed at the back so the reviewers could look at all of them at one time while they read the text. If the manuscript was accepted for publication the tables, figures, and text were split up and sent to different departments then reassembled later. Even though manuscripts are submitted electronically today, the pieces still need to be processed separately. To make this easier, journals require authors to submit their manuscripts with figures and tables separated from the text.

<br/>

## Where to Learn More

[HHMI Data Explorer](https://www.biointeractive.org/classroom-resources/data-explorer) is an interactive web site that you can use to build graphs and learn how different parts go together. In the __Materials__ box on the right side are links for two useful guides you can download that summarize 1) different types of graphs, and 2) different statistical tests.

Kamat, P., Hartland, G., and Schatz, G. 2014. Graphical Excellence. _The Journal of Physical Chemistry Letters_ 5(12):2118-2120.

<br/>
<hr/>

## Instructors' Supplement

Many writing guides tell students to put the table legends, figure legends, tables, and figures on separate pages. This is an archaic rule from pre-digital print publication days that does not help students develop stronger scientific writing skills.

In our experience, keeping the tables and figures separate from the main text is still a pedagogically sound practice, because it helps students learn how to reference their visuals. We strongly recommend letting students put their legends directly below the corresponding tables and figures. This has two benefits. First it connects the two elements visually, reinforcing that the legend is an integral part of the the table or figure. Second, having the figure or table and its legend on the same page speeds up grading for the instructor. 

When localizing your version of this Guide, be sure to provide explicit instructions and examples of the format if you want students to use a different format.
