# (PART) Using Sources {-}
# Citing Literature

We find that a lot of our students struggle with using and citing external sources. Like several other elements of scientific writing, this is partly because how we use and cite sources is different from what you might be used to doing in the social sciences or humanities. To make citing sources more understandable, we divided this part of the Guide into five topics:

* Why you need to support your writing with outside sources (this page).
* How to paraphrase information in sources, so you avoid copying the text.
* How to cite your supporting sources correctly in the main text and Literature Cited section. We will explain a little bit about how citation formats work, and why there are so many different formats.
* Common errors we see students make, and our suggestions for avoiding them.
* How to use a free reference management program to organize your literature sources, attach your own notes, and create your in-text citations and Literature Cited section easily.


## Why Do You Need to Support Your Arguments With Sources? 

We explain elsewhere how [scientific writing is based on making rational, well-supported arguments](http:url.toulmin). In this situation an argument does not mean a verbal disagreement; it means a statement, claim, or conclusion that is supported by logical reasoning and evidence. Evidence includes __observed facts__ that support the claim. Some of the evidence comes directly from the data collected for the experiment and your analysis of those data. Outside evidence comes from prior observations and analysis published by someone else. Using both kinds of evidence makes the supporting argument for your specific conclusions stronger. 


### Not All Sources of External Evidence Are Equal

Scientists are skeptics. They want to be able to judge the quality and reliability of an argument's supporting evidence for themselves. Someone who is reading your scientific writing will want to know where you got the external evidence you used. This is why we need to cite sources. 

When you are trying to support a written argument, you want to use external sources of evidence that are:

* Reliable,
* Peer reviewed,
* Close to the original source, and
* Up to date.

__Reliable__ means that most of your sources of external evidence should be published in established scientific journals (either print or electronic). These journals build a reputation over years or decades for publishing articles that contain accurate observations that can be replicated, and make conclusions based on sound logic and evidence. Sometimes the editors and peer reviewers make mistakes, but their goal is not to confuse readers or hide the truth. Their goal is to share objective information about the natural world around us.

__Peer reviewed__ means other scientists have evaluated the information for accuracy. Just being published somewhere does not automatically make a statement true. Think about how easy it is to publish something on the Web, even if it is not true. Journals use peer review to reduce the chances they will publish inaccurate information. How it works is, when a scientific article is submitted to a journal, the editor sends the article out to other scientists in the field who read the manuscript and give their opinion on the work presented. If there are flaws in the data or logic, they suggest ways to improve the article, or recommend rejection. Almost always the editor's decision whether or not to publish the article is determined by what the reviewers say. This system helps ensure that the published data are reliable, because more than one scientist has reviewed the findings prior to publication. 

We explained elsewhere the [difference in primary and secondary literature](http:url.littypes). Primary literature is the __original source__ for new information, which is why it is always best to use primary literature sources whenever possible. Secondary (review) literature has been interpreted by someone else, so you are one step removed from the original source of the evidence. You are counting on the review author's interpretation of the evidence, not your own. Reviews are useful, but you should try to use primary  sources whenever possible. Fortunately, reviews list their primary literature sources, providing you with a handy, organized set of sources that you can read for yourself.

When you are choosing sources, always look for the most __up to date__ sources you can find. Science grows and changes over time. As we learn new information, we constantly re-interpret what we know from past research. Some fields change very quickly, and what we thought we knew 2-3 years ago has been overturned or re-interpreted. Other fields progress more slowly, but still change over time. When you use old literature sources, you increase the chances of basing your conclusions on outdated facts. 

There are times when you have no choice but to use older sources, especially if you are looking at a topic that only a few people study. Even so, the general rule of thumb is that most or all of your cited sources should be primary literature published in the last 10-12 years.


## How Many Sources Does a Lab Report Need?

There is no simple answer, because it depends on the story you are trying to tell and the argument you are trying to support. Some arguments need more support than others. A basic fact that is not common knowledge (say, the current population of the state of Alaska) might only need a citation showing where you got the number you used. If you are making a more sweeping and broader claim, you need to provide more evidence to support it, and that evidence needs to be very reliable.

The best way to learn how to judge how many sources you need is to read published literature and look specifically at how citations are used. Foundational statements that are central to the whole story usually have multiple independent supporting sources. Observations by one particular lab or an unusual experimental method might have one citation. 
