# Citing Your Sources

Life sciences journals follow the CSE (Council of Science Editors) style guide for print and web publication. Unlike other formats you might have used in humanities or social science classes, there is not a single standard "CSE style." Instead CSE recommends what information citations should contain, then leaves the details of styling up to each journal or publisher. That means if you randomly select primary articles from 10 different life science journals, you will see 10 slightly to very different citation formats. 

__There is no one "right" citation format__. Each format has benefits and drawbacks. We think it is more important to focus on using citations well than to focus on whether commas are in the right place. Still, it is useful if you know a little about different formats so you know how to find the information you need when reading articles.


## Types of In-Text Citations

The two main formats for in-text citations are the name-year format, and various numbered citations formats. Using footnotes for citing sources is rarely used in the sciences.


### Name-Year Format

This style of in-text citations uses the last names of the first 1-3 authors of a source and the year of publication to cite the source. Here is an example of the name-year format in action, using the paragraph from the top of this page:

> Life sciences journals follow the CSE (Council of Science Editors) style guide for print and web publication (CSE, 2017). Unlike other formats you might have used in humanities or social science classes (Johnson, 2018), there is not a single standard "CSE style." Instead CSE recommends what information citations should contain, then leaves the details of styling up to each journal or publisher (Taylor & Coleridge, 2019). That means if you randomly select primary articles from 10 different life science journals, you will see 10 slightly to very different citation formats (Johnson, 2018; Albert, et al. 2010). 

Different journals use slightly different versions of this basic in-text citation format. Some include first name initials (Johnson A.D., 2018), some have or do not have commas or periods, etc. The benefit of this format is that readers can tell the year the source of the evidence you cite was published, and who published it. The trade-off is each name-year citation takes up more space in the text. Some people say it interferes with reading flow too. 


### Numbered List Format

For this in-text citation style, every source listed in the Literature Cited is assigned a number that is used to identify that reference in the main text. Numbers can be in parentheses (3,4,6-9), in brackets [2,5,7-8], or as superscripts<sup>1,4,7,11</sup>. Sources can be numbered in order of first appearance:

> Life sciences journals follow the CSE (Council of Science Editors) style guide for print and web publication (1). Unlike other formats you might have used in humanities or social science classes (2), there is not a single standard "CSE style." Instead CSE recommends what information citations should contain, then leaves the details of styling up to each journal or publisher (3). That means if you randomly select primary articles from 10 different life science journals, you will see 10 slightly to very different citation formats (2, 4). 

For the above example, sources would be listed in the Literature Cited section in this order. 

1. CSE, 2017
2. Johnson, 2018
3. Taylor & Coleridge, 2019
4. Albert, et al. 2010

Sources also can be numbered in alphabetical order of last name of first author:

> Life sciences journals follow the CSE (Council of Science Editors) style guide for print and web publication (2). Unlike other formats you might have used in humanities or social science classes (3), there is not a single standard "CSE style." Instead CSE recommends what information citations should contain, then leaves the details of styling up to each journal or publisher (4). That means if you randomly select primary articles from 10 different life science journals, you will see 10 slightly to very different citation formats (1,3). 

For the above example, sources would be listed in the Literature Cited section in this order. 

1. Albert, et al. 2010
2. CSE, 2017
3. Johnson, 2018
4. Taylor & Coleridge, 2019


In-text numbers are more compact and less distracting, but they do not tell readers anything about who published the source or when. Sources also must be re-numbered every time a source is added or removed or the order of sources changes. 


## What Our Students Use

We use (and recommend) the standard APA name-year citation format in our lab courses. It is well documented and most reference managers (including Zotero) support it. Citations can be downloaded in APA-compatible format directly from PubMed, Web of Science, and many other databases. If a database does not offer APA style as an export option, they usually offer the Harvard citation format, which is very similar so can be updated quickly. Alternatively citations can be downloaded in RIS format, imported into Zotero, and converted to APA format.

We do NOT use the complete APA Style Guide, only the citations formats. For example, APA style allows direct quotes in text, but we do not allow our students to quote sources, even if they are cited correctly. [Learn more about our reasons here.](http://url) 


### Formats For In-Text Citations

APA allows both parenthetical or narrative versions of the name-year in-text format. Parenthetical citations are more common. For example, this is a parenthetical citation for a source with one author:

> Learning theories (Brown, 2014) point to practical ways to improve rats' ability to solve the maze puzzle without requiring more training time.

If the source has two authors, then the parenthetical reference must list them both:

> Sequenced-based analysis of nucleotide usage found patterns similar to what has been reported previously (Gottschalk & Hjortshoj, 2004).

If the source has three or more authors, the last name of the first author is used with "et al.", which is the Latin abbreviation for "and others":

> Sampling methods in ecology have had a longstanding problem with bringing together theories and practical challenges (Albert et al., 2010).

Narrative citations use the name(s) of the source author(s) in the sentence, and put the year in parentheses. For example:

> Alberts, et al. (2010) found that sampling methods in ecology have a longstanding problem with bringing together theories and practical challenges.

In practice we try to discourage our students from using narrative citations, at least when they first start out in scientific writing. They can be a challenge to do well, and are slightly harder to keep properly formatted.


### Formats For The Literature Cited Section

We have outlined the APA formats for the most common types of sources used in lab reports below. The [complete guide to APA Citation Formats](https://apastyle.apa.org/style-grammar-guidelines/references/examples)  is available online. Look there for other citation formats, but remember APA supports many source types that are not appropriate for lab reports.


#### Journal Article with Page Numbers

__Template:__ Lastname, initials of firstname for each author. (Year). Title. Journal, Volume(Issue), firstpage-lastpage. DOI link (if available)

Albert, C. H., Yoccoz, N. G., Edwards Jr, T. C., & Thuiller, W. (2010). Sampling in ecology and evolution: bridging theory and practice. _Ecography_, 33(1), 1028–1037. https://doi.org/doi: 10.1111/j.1600-0587.2010.06421.x

Urban-Lurain, M., Cooper, M., Haudek, K. C., Prevost, L., Smith, M. K., & Sydlik, M. (2014). Expanding a Network for Analysis of Constructed Data Trees. _Computers in Education Journal_, 7(3), 65–81.


#### Journal Article With an Article Number, Not Pages

__Template:__ Lastname, initials of firstname for each author. (Year). Title. _Journal_, Volume(Issue), Article #. DOI link (if available)

Apkarian, N., Henderson, C., Stains, M., Raker, J., Johnson, E., & Dancy, M. (2021). What impacts use of active learning in undergraduate STEM education? _PLOS ONE_, 16(2), Article e0247544. https://doi.org/10.1371/journal.pone.0247544

Ebert-May, D., Derting, T. L., Henkel, T. P., & Passmore, H. A. (2015). Future faculty adopt learner-centered strategies after professional development. _CBE Life Sciences Education_, 14(2), 14:ar22. https://doi.org/10.1187/cbe.14-12-0222


#### Whole Book With Single Author(s)

__Template:__ Lastname, initials of firstname for each author. (Year). _Title_ (edition). Publisher. DOI link (if available)

Gottschalk, K. K., & Hjortshoj, K. (2004). _The elements of teaching writing: A resource for instructors in all disciplines_. Bedford/St. Martin’s.

Lantz, B. (2013). _Machine Learning with R: Learn How to Use R to Apply Powerful Machine Learning Methods_. Association for Computational methods. https://dl.acm.org/doi/10.5555/2588158


#### Whole Book With Editors

__Template:__ Lastname, initials of firstname for each editor. (Ed or Eds). (Year). _Title_ (edition). Publisher. URL or DOI link (if available)

Anson, C. M., & Moore, J. L. (Eds.). (2017). Critical transitions: Writing and the question of transfer. The WAC Clearinghouse, University Press of Colorado. https://wac.colostate.edu/books/perspectives/ansonmoore/


#### Chapter in an Edited Book or Ebook

__Template:__ Lastname, initials of firstname for each author. (Year). Chapter Title.  In initials of firstname, lastname of book editor(s) (Eds.), _Book Title_. (edition if needed, pp. in book). Publisher. URL or DOI link (if available)

Rothermel, B. A. (2006). Automated writing instruction: Computer-assisted or computer-driven pedagogies? In P. F. Ericsson & R. H. Haswell (Eds.), _Machine scoring of student essays: Truth and consequences_ (pp. 199–210). Utah State University Press. https://archive.nwp.org/cs/public/download/nwp_file/16663/machine.pdf?x-r=pcfile_d

Pitelka, D. R., & Child, F. M. (2016). Ciliary structure and function. In: S. S. Gilman, & S. N. Hunter (Eds.), _Biochemistry and Physiology of Protozoa_ (3rd ed.,  pp 131–198). New York Academic Press.

Tassone, A., Sciamanna, G., Bonsi, P., & Martella, G. (2011). Experimental models of dystonia. In: J. Brotchie, E. Bezard, & P. Jenner (Eds.), _Pathophysiology, Pharmacology, And Biochemistry Of Dyskinesia: International Review of Neurobiology_ (pp 551-572). New York.


#### Official Report by a Government Agency

__Template:__ Publishing Agency. (Year). Title. (Publication ID#). Parent Department. URL for source or DOI link.

President’s Council of Advisors on Science and Technology. (2012). Engage to Excel: Producing One Million Additional College Graduates with Degrees in STEM. Executive Office of the President. https://obamawhitehouse.archives.gov/sites/default/files/microsites/ostp/pcast-engage-to-excel-final_2-25-12.pdf


#### Official Report with Individual Authors

__Template:__ Lastname, initials of firstname for each author on report. (Year). Report Title.  (Report ID# if one is present). Publisher. URL or DOI link

Pellegrino, J. W., & Hilton, M. L. (Eds.). (2012). Education for life and work: Developing transferable knowledge and skills in the 21st century. The National Academies Press. DOI: https://doi.org/10.17226/13398

Fry, C. L. (Ed.) (2014). Achieving Systemic Change: A Sourcebook for Advancing and Funding Undergraduate STEM Education. Association of American Colleges and Universities. https://www.aacu.org/sites/default/files/files/publications/E-PKALSourcebook.pdf


#### White Paper With a Group As Author

__Template:__ Name of Group. (Year). Title. [White paper]. Publisher or sponsor (if different). URL or DOI link 

R Studio Development. (2019). Scaling R for Enterprise-level Performance, Scalability, Ease of Production Deployment, and Security. [White paper.] Oracle, Inc. https://www.r-bloggers.com/2013/06/bringing-r-to-the-enterprise/


####  White Paper With Individual Authors

__Template:__ Lastname, initials of firstname for each author. (Year). Title. [White paper]. Publisher or sponsor. URL or DOI link 

Greenwood, M. (2001). Implementing a Vector Space Document Retrieval System. [White paper]. University of Sheffield. http://www.dcs.shef.ac.uk/~mark/nlp/pubs/vspace.pdf


#### Conference Presentation or Abstract

__Template:__ Lastname, initials of firstname for each author. (Year, date). Title [descriptor]. Conference  Name, Location. URL or DOI link (if available)

Describe the kind of presentation with a 1-2 word phrase like [Conference session], [Paper presentation], [Abstract], or [Poster session] in square brackets after the title. 

Loper, E., & Bird, S. (2002, 10-August). NLTK: The Natural Language Toolkit [Conference presentation]. Proceedings of the ACL-02 Workshop on Effective Tools and Methodologies for Teaching Natural Language Processing and Computational Linguistics, Philadelphia, PA. https://doi.org/10.3115/1118108.1118117

Scheffler, I.E., Yadava, N., & Potluri, P. (2004, June 30-July 3). Molecular genetics of complex I-deficient Chinese hamster cell lines [Conference session]. 6th European Meeting on Mitochondrial Pathology, Nijmegen, Netherlands. DOI 10.1016/j.bbabio.2004.08.002


#### Published Dissertation or Thesis

__Template:__ Lastname, initials of firstname of author. (Year). Title. (Publication ID#) [Doctoral dissertation, Institution]. Database or repository. DOI link (if available)

Sullivan, T. J. (2017). Molecular Ecology, Disease Ecology, and Candidate Genes for Pathogen Resistance in the Blue Crab _Callinectes sapidus_. (Publ.# 10273194) [Doctoral dissertation, University of Louisiana at Lafayette]. ProQuest Dissertations. https://pqdtopen.proquest.com/doc/2309521814.html?FMT=AI


### Using and Citing Electronic Materials

We see students make a LOT of mistakes when using electronic sources. That is why we do not let students in our program use them as their main sources of information. If you plan to use electronic materials as part of your cited sources, you need to be very careful to cite them correctly.

The most common mistake we see is students using a URL or web address for an article as a citation. __This is not acceptable in scientific writing.__ A valid citation for an electronic source still has the names of the authors, name of the resource, and when and where it was accessed. Never use just the URL from a Pubmed, Web of Science, or Google Scholar page, or a DOI link on its own to identify or cite a source. 

The other common mistake we see students make is using unreliable web sources. General access web pages are not acceptable sources because the content is not peer reviewed for accuracy by subject matter experts. Wikipedia should not be used as a sources for that reason. Electronic sources need to be peer reviewed, and preferably primary sources.  

In general, you can safely use electronic materials obtained from official publications of government agencies (site URLs usually end with “.gov”). Web sites of scholarly research projects associated with a research institution or university are acceptable sources, but should never be the sole source of information. 

Some web pages have content that changes over time and is not archived. If this is true for the site you are referencing, include the date you retrieved the information in the reference.


#### Citing a Web Page Authored By a Government Agency

Name of the authoring agency. (Year). _Page Title_. Parent agency. URL link 

National Institute of Mental Health. (2018, July). _Rates of anxiety disorders_. U.S. Department of Health and Human Services, National Institutes of Health. Accessed January 9, 2020, from https://www.nimh.nih.gov/health/topics/anxiety-disorders/index.shtml


#### Citing a Web Page With Named Authors

Lastname, initials of firstname for each author. (Date of publication, or n.d. for "no date"). _Page Title_.  Sponsoring group or agency. URL link

Giovanetti, F. (August 24,2021). _An unprecedented peek into life of 17,000-year-old mammoth._ National Science Foundation. https://www.nsf.gov/discoveries/disc_summ.jsp?cntn_id=303320&org=NSF&from=news


## Advanced Topic: What Exactly IS a DOI?

As more material became available online in the 2000s, publishers adopted a new way to track materials called __digital object identifiers__ (DOIs). Often DOIs are embedded as web links, but even when a DOI is not an active link, you can find the original source by copying the DOI and using it as a search term in Google. 

Started by the major journal publishers, DOIs have grown into nearly universally recognized identifiers. What makes them so useful is that they are catalogued in one central electronic database. If the location where a particular source is stored changes, the publisher is required to update the link to it in the central database. As a result, researchers know where to access a DOI-tagged source regardless of which publisher originally produced it. 

Currently the Council of Science Editors does __not__ recommend using DOIs as the sole form of citation, for two reasons. First, DOIs do not tell the reader anything about the authors or source of the information, only where it is located online. Second, DOIs are not useful when a reader does not have access to a web browser. That is why APA and other citation formats include the DOI at the end of a citation, but do not use it in place of the traditional information (authors, year, etc.)

