# Using Zotero to Manage References {#zotero520}

Reference managers are software programs that collect and archive data on articles, books, web pages, etc., and output citations in a standardized format. There are several commercial programs (EndNote, Reference Manager, ReadCube, RefWorks, etc.) as well as open-source projects ([Mendeley](https://www.mendeley.com/), [EasyBib](https://www.easybib.com/), [BibTex](http://www.bibtex.org/), Zotero). If you already use one of these programs, stick with it. If you do not use one yet, we suggest starting with Zotero.

## What IS Zotero {-}

__[Zotero](https://www.zotero.org/)__ is a free web-based reference manager developed by the Corporation for Digital Scholarship, a nonprofit organization dedicated to the development of software and services for researchers and cultural heritage institutions. You do not need an institutional license, so your account travels with you anywhere you go. 

At first, it might seem like Zotero (or any reference manager) is not worth the time and effort. Yes, it does take some time to set up initially, but the more you use it, the more time you will save by not having to format citations by hand. Zotero also reduces the chances that you format a citation incorrectly, or cite a source that you do not actually use. 


## How to Get Zotero {-}

The best place to start is Zotero's [main documentation page](https://www.zotero.org/support/). There is a handy Table of Contents listing all of the topics, not just the ones we have selected below. 

* Getting Started With Zotero
    + [Installation](https://www.zotero.org/support/installation) is where you start. The instructions are long only because Zotero works on so many different types of computers. It really is easy to get installed.
    + [Quick Start Guide](https://www.zotero.org/support/quick_start_guide) gives you an overview of how to use Zotero.
    + [Frequently Asked Questions](https://www.zotero.org/support/frequently_asked_questions) answers the most common problems people have with installing and using Zotero.
## Adding References to Zotero {-}


## Using Zotero {-}

These pages should get you up and running quickly.

* Getting Stuff Into Your Library
    + [Adding Items](https://www.zotero.org/support/adding_items_to_zotero) explains how to capture references from public databases so you do not have to type them. This is the page that you will need to refer to a LOT until you get used to Zotero.
    + [Retrieve PDF Metadata](https://www.zotero.org/support/retrieve_pdf_metadata) tells you how to let Zotero import a citation directly from a downloaded PDF. This usually works well for most articles published in the last 20 years, but might not for older articles.
    + [Collections and Tags](https://www.zotero.org/support/collections_and_tags) explains how to take one big list of citations (your library) and pull out specific citations to build a bibliography.
* Generating Bibliographies, Citations, and Reports
    + [Creating Bibliographies within Zotero](https://www.zotero.org/support/creating_bibliographies) explains how to build a list of literature citations entirely within Zotero. This method takes a little longer, but gives you maximum control over the process.
    + [Word Processor Integration](https://www.zotero.org/support/word_processor_integration) explains how to set up Zotero so you can add citations to articles while you type. This makes it MUCH easier to build your list of citations at the end.
    + [Citation Styles](https://www.zotero.org/support/styles) explains how to pick the citation style you are expected to use, and set Zotero to use it.

* Getting the Most Out of Zotero
    + [Knowledge Base](https://www.zotero.org/support/kb) goes into more detail than the Frequently Asked Questions.
    + [Locate Menu](https://www.zotero.org/support/locate) describes how to look up references in your institution's library or other databases from right inside Zotero.
    + [Community-developed Video Tutorials](https://www.zotero.org/support/screencast_tutorials) are YouTube videos that walk you through every step of Zotero.


Zotero has many additional features that are worth exploring once you can use the basic tools comfortably. Check too to see if your school has local guides on using Zotero or a similar web application.
