# Strategies for Writing {-}

The first few times that you write for a scientific audience, you might not know how or where to start. That's okay; there is more than one way to approach the task. We suggest using one of these two general approaches to writing, at least until you develop a workflow of your own. The basic steps are the same, just placed in a different order.

## Writing to an Outline

We mentioned before that the Step by Step Guide to Experimental Design can be used as an outline for writing your report. This is a good strategy to use if you like to work through a writing assignment in order, and do not like to skip around. These steps will provide you with a rough draft that you can go back and revise later.

__For the Introduction__

1. Summarize your background information and observations. Ask yourself:
    + What background information do others need to know to understand my study? 
    + What have other scientists learned that is relevant to answering my question? What is my source for that information? Is it cited properly?
2. Describe the specific biological question you want to try to answer. State your question in the form of a biological hypothesis. 

__For the Methods__

3. Describe the experimental setup you used.
    + How were the control and treatment groups manipulated?
    + How did you collect measurements?
    + What controls and replicates did you have? 
4. Describe which variables are relevant to the question you are asking, and which ones are your dependent and independent variables. 
5. Describe the statistical tests you use to analyze the data. Use the variables to state your the question in the form of a statistical null hypothesis and alternate hypothesis. 

__For the Results__

6. Organize your summary results into tables and figures.
7. BRIEFLY summarize your results, but do not interpret them yet. Refer to your tables and figures, and number them in the order they first appear.
8. Report the results of the statistical tests comparing control and test groups.

__For the Discussion__

9. State whether or not you rejected or failed to reject your statistical null hypothesis. 
10. Explain what your summarized and analyzed data are telling you. Refer back to the tables and figures as needed.
    + Don’t just look at the outcome of the statistical test(s) and blindly assign a conclusion to your work. 
    + Interpret the results in light of your original hypothesis.
11. Talk about how your results fit into a bigger picture. 
    + If you use the work of other scientists, be sure to provide a citation for the source.

__Finishing Up__

12. Write an ~200-word summary of your entire report. This will be your Abstract. Include information from every section.
13. Make sure every cited source in the text has an entry in the Literature Cited section.


## Writing From the Middle Outward

Here your strategy is to write your report in 3 segments as separate 1/2- to 1-page pieces. For each segment you start by writing or creating the main piece. Then you write the parts that lead up to it. You can write the 3 segments in any order, but it is better if you complete a rough draft of one segment before starting another. 

This is a good strategy to use when you are not completely sure what readers need to know to interpret your results. You can write the middle segment first, and use that to decide what to include in the front and back segments. Once you have the 3 segments written, you add text to make connections between them.

__Start With the Middle Segment__

This will become your __Methods__ and __Results__ sections. 

1. Describe the experimental setup you used.
    + How were the control and treatment groups manipulated?
    + How did you collect measurements?
    + What controls and replicates did you have? 
2. Describe which variables are relevant to the question you are asking, and which ones are your dependent and independent variables. 
3. Organize your summary results into tables and figures.
4. BRIEFLY summarize your results, but do not interpret them yet. Refer to your tables and figures, and number them in the order they first appear.
5. Describe the statistical tests you used to analyze the data. Use the variables to state your the question in the form of a statistical null hypothesis and alternate hypothesis. 
6. Summarize the results of the statistical tests comparing control and test groups. Write the results out in the reporting format described on the statistics pages.

__Front Segment__

This will become your __Introduction__.

7. Start by summarizing your central question question, and your testable hypothesis. 
8. What prior observations that you or others made led you to that hypothesis? Put that information __before__ your hypothesis statement. 
9. Now, what background information does someone need to know to see why the hypothesis you want to test is important? Put that information __before__ your prior observations. 

__Back Segment__

This will become your __Discussion__ section.

10. State whether or not you rejected or failed to reject your statistical null hypothesis. 
11. Explain what your summarized and analyzed data are telling you. Refer back to the tables and figures as needed.
    + Don’t just look at the outcome of the statistical test(s) and blindly assign a conclusion to your work. 
    + Interpret the results in light of your original hypothesis.
12. Talk about how your results fit into a bigger picture. 
    + If you use the work of other scientists, be sure to provide a citation for the source.

__Finishing Up__

13. Write an ~200-word summary of your entire report. This will be your Abstract. Include information from every section.
14. Make sure every cited source in the text has an entry in the Literature Cited section.



