# How to Construct a Good Argument
## The Upside of Arguments

Something we see a lot in scientific writing are arguments. In this situation, an argument does not mean a verbal disagreement, but rather a statement or claim backed by logical reasoning and evidence.

In 1958, the British philosopher and educator Stephen Toulmin published a book called "The Uses of Argument," in which he laid out a practical framework for deconstructing and analyzing arguments. We can use his framework to __construct__ better scientific arguments too.

Toulmin wrote that most “practical arguments” could be broken down into six interrelated components. Many disciplines use slightly different versions of this framework as a useful way of thinking through and evaluating arguments systematically. To make it easier to use, we will give some of Toulmin's steps more familiar names. Do not get hung up on the terms; focus on how the parts come together to produce a good argument.

1.	Claim, Conclusion, Recommendation, or Action:
The position or thing being argued for; the conclusion of the argument; the recommended or planned course of action. It is what the speaker or writer wants to convince their audience is true. Usually the claim statement will be obvious, but sometimes it will be implied or inferred.

2.	Evidence (sometimes called Grounds):
Evidence is the __observed facts__ used to support the claim. Evidence can be direct observations (like the results of an experiment) that the writer made, or evidence can be prior observations made by someone else. Using both kinds of facts makes for a stronger argument.

3.	Reasoning (what Toulmin called Warrant):
Principles or a chain of reasoning that connects the grounds/evidence to the claim. Reasoning is how the observed evidence leads logically to the claim or conclusion.

4.	Backing:
This is external evidence, support, justification, or rationale that backs up the _reasoning_. The main difference between evidence and backing is that evidence supports the claim, and backing supports the reasoning statements themselves.

5.	Rebuttal/Reservation:
Sometimes evidence can be interpreted more than one way. A rebuttal is the exceptions to the claim, or counter-examples and counter-arguments that weaken the connection between the evidence and the claim/conclusion.

6.	Qualification:
Limits on claim, evidence, or reasoning. Essentially, when the argument is NOT valid anymore.


## Putting Claim-Evidence-Reasoning to Work

We make casual argument statements in conversations all of the time. In these situations some parts of our argument may be implied or assumed. When a scientific writer makes an argument, we cannot make these same assumptions; we have to make our arguments sound, clear, and precise. We do that by paying attention to details.

Let's use the Toulmin model to assess some (slightly silly) arguments. Suppose you are hiking in the woods with three friends. Your first friend says,
    ``"I bet there are bears here." ``

They just made a claim, but they provided no evidence or reasoning to support it. On its own this is a pretty weak argument.

If your first friend instead says,
    ``“There’s a bear!”``

They have made a clear claim, and they are implying that they have evidence, but you do not know what kind of evidence or how they decided it indicates a bear.

If they say,
    ``“I see a bear!”``

Now you know their claim and what kind of evidence they are using, but you still do not know anything about their reasoning. Does your friend actually know what a bear looks like, or how big it is? They might be looking at a raccoon or groundhog.

Your second hiking partner then says,
    ``“I see a big pile of poop and bear tracks, so what you see must be a bear!”``

There is clear claim, evidence, and reasoning now, but we are not out of the woods yet. Do you trust your second friend knows what bear tracks look like? How old is the poop pile? How do you know the bear poop and tracks are from the same animal your first friend saw?

Now suppose your second friend instead had said,
    ``“There’s a big pile of poop and huge tracks, so it's not a bear, it's a sasquatch!”``

They are making a claim that goes against what we have observed in the past. They need to provide a lot more compelling evidence. Their reasoning is flawed too, because they did not rule out other possible sources (like a bear).

Your third hiking companion says,
    ``“There’s a big pile of poop and tracks that look like the picture of bear tracks in the field guide; no other species lives here, and the warden said black bears have been spotted recently. So it’s probably a black bear!”``

Now we have a very robust argument. There is a clear claim based on multiple pieces of evidence, clear reasoning, and information that addresses a possible rebuttal. (Of course, all three of you are now dead because you spent 10 minutes building a robust argument rather than running away from the bear!)


## Assessing Arguments Systematically
There are five simple but powerful questions we can use to assess any argument we read or hear, AND check the strength of our own arguments as we write.

1. Is the claim itself stated clearly?
2. Is the claim based on clearly stated and relevant evidence?
3. Is the reasoning that connects the evidence to claim clear and sound?
4. Can the claim be rebutted? Is there another possible explanation? Is there conflicting evidence?
5. Are the limits of the claim clear? Does the writer or speaker provide enough information that their audience knows when the claim does not apply or is not true?

Remember, your goal in scientific writing is to make a strong argument that supports a claim using multiple pieces of evidence and sound reasoning.

