# Peer Reviewing Lab Reports {#peerreview630}

## Why Does Peer Review Work?

Earlier in this Guide we said that the best way to learn scientific writing skills is to read scientific writing by others. That is why we routinely have our students read primary literature articles BEFORE they try to write one. Another way to build your scientific writing skills is peer reviewing other students' reports. 

Some of our students have said they do not like peer review because they do not get very good feedback from their partner. That does happen, especially when everyone is just starting out as scientific writers. Even so, the most important lessons you will learn probably are not what your reviewer tells you, but what you discover when you read THEIR work.

Usually in a peer review you are reading a report on a similar topic as your own. You already know their basic methods and how they should be reporting their results. You get to see how they described their procedures, what background information they provided, and how they interpreted their results. If you pay close attention to how they organized the content, you can see others ways to describe the same basic information, and decide for yourself if their approach does or does not work. When you meet with the student whose report you reviewed, you can see if what they wrote (and how you interpreted it) is what they actually meant to say. If you think about what you learned from reading their work as you revise your own report, you should start to see the points where you could be more concise or clearer, write a better logical transition, or provide missing details.

The first few times you peer review another student, you are training yourself to look at writing more critically overall. As you and your classmates gain experience, you will be able to provide more specific and meaningful feedback to each other. 


## General Workflow

The report you submit for peer review should NOT be a rough draft, but in a final form that you think is ready to hand in for a grade. You will partner with another student who is NOT one of your regular lab partners, and so did not work on your experiment with you. 

1. Your review partner will read your lab report, then write down their comments and explain what improvements you need to make. You will do the same for their report. 
    + Usually both of you will follow the same criteria that your final report will be graded on.
    + Try to imagine yourself as the instructor, not as another student. What would they be looking for?
2. First, skim the entire paper. This should take 2–3 minutes for a 4– to 5–page paper.
    + Make sure that all of the major sections and parts are there (Introduction, Discussion, figures, etc.) 
    + Try to get a general idea of the structure and flow.
3. Now re–read the entire paper again carefully. 
    + Mark larger questions or points you want to discuss with an arrow. Include a couple of words so you know what you want to say or ask when you get back with your partner. 
    + If you see typos, grammar, or other mechanical errors, circle them. You do not need to correct them, just mark them so your partner can find them.
    + Pay attention to the logical flow. 
        - Is the background DIRECTLY relevant to the ideas being presented and experiments conducted?
        - Does one idea naturally lead to the next? Is the progression logical?
    + Is the description of the methods sufficient for you to understand what they did? 
        - Could you replicate their experiment if needed? 
        - Is there anything that could be removed without making the report less clear?
    + Are the results summarized accurately and concisely? Are the most important results emphasized or highlighted? 
    + Does the discussion help you understand the importance of the results? 
        - Do you know more now than when you started reading this paper?
        - Does the paper help you see why that knowledge if useful or important?
        - Are the final conclusions of the paper supported by the data presented, or is there another logical alternative?
    + Put an “X” to mark any places where the report does not conform to the standard format your instructor has defined for references, margins, spacing, etc.
4. If your instructor has provided a review summary sheet, fill it out as instructed.
5. Once you both finish reading, discuss your comments on each others' work. As you talk, pay attention to how __your choices__ of phrasing, logical flow, and other elements affected how your partner interpreted what you wrote. During the discussion:
    + Be honest but polite. EVERY writer can make improvements to their work. 
    + Ask questions if you need clarification.
    + Point out things you liked, not just things that need work.
    + If you and your peer reviewer disagree on a particular item, ask your instructor for their suggestions, or check the Resource Guide.

<hr/>
__Note:__ Many people get defensive when someone critiques their work. This just impedes your growth as a writer. Tell your ego it has to sit down and be quiet for an hour or so, and pay attention to what your reviewer says. If they misinterpret what you meant by a passage, it often is your fault as the writer, not theirs as a reader.
<hr/>
<br>

## Sample Review Summary Sheets

### Narrative Summary Sheet

This summary uses open-response questions instead of a detailed rubric. It is the better option when students do not have much prior experience with peer review.

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0lax"><strong>Features to Look For</strong></th>
    <th class="tg-0lax"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comments&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">1. Basic criteria:<br>* Are all of the required sections present?<br>* Does the report meet the minimum essential requirements?</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">2. Intellectual content, logic and reasoning:<br>* Can you follow the author's logic?<br>* Are the ideas presented in an order that you can understand?<br>* Does the author refer to and connect their data to a larger story?</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">3. Technical elements:<br>* Are the results summarized and reported correctly? Is any raw data presented?<br>* Are the citations in the text and Literature Cited used correctly?<br>* Are there sources given for all information that is not common knowledge?<br>* Does the text reference the data tables and figures?<br>* Are the tables and figures correctly formatted? Can you interpret them easily? <br>* Do tables have accompanying legends? Are legends complete so that the meaning of the figure is clear?</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">4. Writing quality:<br>* Is the writing clear, concise, and in proper English?<br>* Are there misspellings, unclear sentences, sentence fragments?<br>* Is any part of the report too short or too long?</td>
    <td class="tg-0lax"></td>
  </tr>
</tbody>
</table>
<br>

### Bins-Based Summary Sheet

This summary uses the specific criteria that GTAs might use to assign a grade a report. Students need to have some prior experience with reading and writing reports before they can complete this form accurately.

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-cly1{text-align:left;vertical-align:middle}
.tg .tg-0lax{text-align:left;vertical-align:top}
.tg .tg-nrix{text-align:center;vertical-align:middle}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0lax"><span style="font-weight:bold">Basic Criteria:</span><br>If ANY of these 5 items is missing, a report is Unacceptable</th>
    <th class="tg-cly1">Does Report Meet Criteria?<br>Circle ONE</th>
    <th class="tg-cly1">Notes or Comments</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax"><span style="font-weight:bold">Lab report contain a hypothesis</span>, clearly articulated research goals.</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax"><span style="font-weight:bold">Lab report is clearly organized. </span>Each section reflects structure of a scientific paper. <br>For example, Results section does not contain interpretation.</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax"><span style="font-weight:bold">Data figures, tables</span> are clear and informative.</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax"><span style="font-weight:bold">Report has an interpretation of results. </span><br>Discussion states if hypothesis is supported and why.</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax"><span style="font-weight:bold">Primary literature used to back up statements in Introduction, Discussion.</span><br>Supporting literature may be used in other sections too.</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax" colspan="3"><span style="font-weight:bold">Flaws in Technical Criteria</span>:</td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Report contains raw data</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- There are several errors in data summaries (graphs, tables)</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Improperly applied statistics</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Claims not supported by evidence provided or sources cited</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Connection between claims, evidence, reasoning is unclear</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Citation errors or misuse</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- No references to figures, tables</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax" colspan="3"><span style="font-weight:bold">Flaws in Writing Quality, Style</span>:</td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Unclear wording</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Poor flow</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Lacks clear thought process, plan connecting parts</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Imprecise language</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Wordy, not concise</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Not technically presented; “emotional” language</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">&nbsp;&nbsp;- Distracting elements detract from clearly understanding outcomes.</td>
    <td class="tg-nrix">YES  or NO</td>
    <td class="tg-0lax"></td>
  </tr>
</tbody>
</table>


