# Training Teaching Assistants {#tatraining720}

In our program, undergraduate lab reports are graded by GTAs who direct the lab sections, not faculty. The majority of our novice GTAs have not graded student work before. They bring a variety of past experiences, biases, and misonceptions with them when they join our program. Even seasoned GTAs can bring confounding preconceptions from their previous schools, or try to incorporate writing conventions that are specific to their research field. Also, many GTAs have limited scientific reading and writing experience so may have less confidence in their ability to judge the work of students who are close to their own age. To compensate, GTAs may focus on obvious mechanical and formatting errors, citation punctuation, and similar items that can be corrected by copy-editing. 

We have 3 training activities that help GTAs internalize and start to use our bins-oriented strategy[explained elsewhere](#commenting710). 

* A general orientation in two parts: during the first day of orientation for new GTAs, and during lab prep meeting ~ 2 weeks before GTAs begin teaching writing for the first time.
* Marking up previously graded reports. Before grading their first time, GTAs are given a set of training reports and asked to grade them using our bins-based scoring. After grading, GTAs discuss their scores and comments with experienced graders.
* Round-robin scoring. Each GTA selects 4 reports from their first set of the semester, score them, then passes the 4 reports to another TA who also scores them. Scores and discrepancies are discussed in the next lab prep meeting.

Over time, GTA grading performance and priorities can drift. We find that having experienced GTAs work with incoming novice GTAs each fall semester significantly reduces this. Experienced GTAs must explain their specific interpretation of the grading guidelines to their peers, and most are quick to compare and self-correct.

We also check GTAs' report grading at least once each semester. GTAs grade, comment, and return student reports through the institutional LMS. We download 4-6 randomly selected reports for each GTA, and check to see the types and numbers of comments they are attaching to reports. At the end of each semester, we run correlation analysis comparing students' lecture and lab grades. Historically, student lecture and lab grades have a correlation > 0.85, and correlation slopes are essentially identical between GTAs. A difference of >3% in median report scores relative to other GTAs in the same coure, a lecture/lab grade correlation < 0.8, or a correlation slope that differs from other GTAs, are all indicators that a particular GTA may not be grading according to the criteria. We meet with the GTA to discuss their strategy, and look for ways to make corrections going forward.   


