# Adding Tables and Figures to Reports {#visualembed440} 

## How to Number Tables and Figures in Your Reports

Figures and tables are numbered separately, in the order they are referred to in your text. Do not mix the table and figure numbers; keep them separate. For example, imagine you wrote a lab report containing 2 summary tables and three graphs. In the main text you refer to the first table, then two of the figures, then the second table, and finally, the third figure. You would number the tables and figures as:

* Table 1
* Figure 1
* Figure 2
* Table 2
* Figure 3


## Where to Put the Tables, Figures, and Legends

There is no one correct way to add your tables, figures, and legends to your lab report. Your instructor will tell you what order they want you to use, and how items should be arranged. 

__In our program__, students put their tables and figures in their reports after the Literature Cited, starting on a new page. Tables come first, and should be inserted in numerical order, with the legends directly below their corresponding table. Next come the figures, again in numerical order, with the legends directly beneath the corresponding figure. There are examples of the layout in Appendices A-C.

<br/>
<hr>
<br/>

## Instructors' Supplement

Many writing guides tell students to split the table legends, figure legends, tables, and figures to separate pages. This is an archaic rule from pre-digital print publication days when parts of a manuscript had to be kept separate because each went to different teams to prepare them for printing. It does not help students develop stronger scientific writing skills.

In our experience, keeping the tables and figures separate from the main text is still a pedagogically sound practice, because it helps students learn to reference their visuals. We strongly recommend letting students put their legends directly below the corresponding tables and figures. This has two benefits. First it connects the two elements visually, reinforcing that the legend is an integral part of the the table or figure. Second, having the figure or table and its legend on the same page speeds up grading for the instructor. 

When localizing your version of this Guide, provide explicit instructions here about the format you want students to use.
